### ISSUE TITLE
Swagger Spec Consolidation

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1088]
## Summary

Leverage common request, response, error data models for the v1 and v2 swagger specification.

## Background

EasyCLA needs to support both v1 and v2 swagger specifications to support the current system and the new LFX/CommunityBrige UI.  While generating the swagger specifications, we identified a way to leverage common data models between both specs.  This approach allows us to share data models and not generate duplicates under separate packages while making the swagger specification easy to edit (avoids duplicate copy/paste entries in multiple files.  This approach worked, but the auto-generated API-Docs were not begging rendered properly (v2 response models were null).  @prasannamahajan has identified a nodejs tool which will help us by taking common YAML files with models and merge the common specs into a v1 spec and a v2 spec.

This task is to implement this approach.

## Tasks

- [x] Identify the approach and design pattern for utilizing a set of common data models written in swagger which can be imported/used by the main swagger specification. E.g. 

events.yml + signatures.yaml + cla-groups.yaml + companies.yaml => v1 sepc
events.yml + signatures.yaml + cla-groups.yaml + companies.yaml => v2 sepc

- [x] Update the EasyCLA Golang build process to incorporate the tool(s) and process
- [x] Update the EasyCLA handler code such that API endpoint handlers return the appropriate data models (develop common routines to convert and return the appropriate responses).

## User Story

As an API developer, I want to maintain a common set of request and response models between both v1 and v2 without having to copy/paste/duplicate spec fragments.

## Assumptions

- API request, response, and error models are common between v1 and v2 (this ticket does not apply to endpoints/models that are different).

## Acceptance Criteria

1. EasyCLA system builds using/leveraging common data models
1. API Docs are rendered correctly

## References

- [Swagger Ref](https://swagger.io/docs/specification/using-ref/)

**Comment by prasannamahajan** [comment]
This is implemented and deployed to dev.
