### ISSUE TITLE
Contributor Console API - Organization Service Support

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1130]
## Summary

As part of the v2 Contributor Console UI redesign, we want to query the Organization/Company List from SalesForce.

## Background

v1 and v2 API should query the Org Service to fetch the *complete list* of known/existing companies. The API should support look-ahead/partial match as the user types.

This is for [Contributor Console PRD](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2) table 2 step 2; table 3 step 2; table 4 step 1.

1. User Searches => from v1 or v2 Contributor Console => Search Org Service via Filter => User Selects (we get: SF Org ID + Name + Owner)
1. Search the EasyCLA Company Table => Search by External ID => Find match?
1. If Company match found => return this as the company id => continue flow
1. If Company match not found => Go to user service and lookup Owner => search EasyCLA Users table for the match
1. If User match found => Create EasyCLA company => assign owner as the manager => continue flow
1. If User not found => create EasyCLA user entry, assign company => Create EasyCLA company => assign owner as the manager

## Tasks

- [x] Update the existing company search in the contributor conosle to query the Org Service for the list of companies. Present this list to the UI.
- [x] Once the user selects the company, we need to ensure the EasyCLA company table includes the company record (add if missing / confirm external ID is set).  Add Org Service admins to the EasyCLA company_acl.

## User Story

As a contributor, I want to query the complete list of companies so that I can select my company.

## Assumptions

- [x] Common API routine - should be leveraged by both v1 and v2 Contributor Consoles.

## Questions

List any questions or clarifications that are needed to addressed to satisfy this request.

1. [...] Question 1...
1. [...] Question 2...

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by prasannamahajan** [comment]
API: GET v3/organization/search?companyName=
Response:
`{
  "list": [
    {
      "organization_id": "string",
      "organization_name": "string"
    }
  ]
}
`

API: GET v3/company/external/{companySFID}
Response:
`{
    "companyACL": [
        "prasanna.mahajan",
        "prasanna1993"
    ],
    "companyExternalID": "0014100000Te0fMAAR",
    "companyID": "eb4d7d71-693f-4047-bf8d-10d0e7764969",
    "companyManagerID": "54300b8b-643f-11ea-b6cd-80ce62109433",
    "companyName": "Pinterest",
    "created": "2019-07-15T15:28:33.127Z",
    "updated": "2019-07-15T15:28:33.127Z"
}`

**Comment by prasannamahajan** [comment]
added organization_website in response.

**Comment by prasannamahajan** [comment]
API: 
1. [https://api.dev.lfcla.com/v3/api-docs#operation/searchOrganization](url)
2. [https://api.dev.lfcla.com/v3/api-docs#operation/getCompanyByExternalID](url)


cc @dealako @nirupamav 
Assumption for implementation:
company will have company-admin role assigned in acs.

2nd api will fail if easycla database does not have company present in its db and acs does not have company-admin role assigned for this company.

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**_Endpoint https://api.dev.lfcla.com/v3/api-docs#operation/searchCompany_**
**1. 500 internal server is displayed when trying to search with special characters. The company names I tried to search is already existing in org service**
Few other companies that exist in org service have same issue
Famous Dave's of America, Inc.
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b1523cf8-3039-43fc-b6b1-80ccd2912bfd)

2. Anything before comma in search criteria is not considered to fetch search results
For e,g. I was trying to find **Samsung Electronics America, Inc.** and observed all companies that has **Inc.** is fetched
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/73fb5717-9a88-4087-9d8d-b11c64caa2c2)

**3. Empty object is returned when trying to search for company with name _Landis+Gyr North America_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cde9d40c-ebb5-4190-a7f7-1aa79241b68e)
Company exists in org service
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e87bc559-53c4-4f0f-a9d2-ecdbc5e78331)

**_Endpoint https://api.dev.lfcla.com/v3/api-docs#operation/getCompanyByExternalID_**
@dealako 
What is the difference between company_acl and signature_acl
As of now the endpoint is fetcing company_acl

**Comment by dealako** [comment]
Our get company by External ID search:

1. Attempts to locate the company record in the EasyCLA database by external (SF) ID.  If found, returns the Company Record data model.
2. If we were unable to locate the Company Record in our EasyCLA database by the external ID, we attempt to locate the record in the SalesForce database via the Platform Organization Service API call.
3. If we find the SF Organization Record, we lookup the SF company admin associated with the company.
4. If the company admin does not exist in our EasyCLA database, we create the corresponding user record in the EasyCLA database.
5. If we find the SF Organization Record, we create the Company Record in our EasyCLA database.  We then return this record as a Company Record data model.

The company ACL is essentially the SF Company Admin - the same concept.

For this API call - we are not discussing signature ACL - this is only a company query - so, we show the company ACL - which is the company admin.

**Comment by dealako** [comment]
@rinkeshbhutwala I am assigning you this task. Can you please review the feedback that @nirupamav has provided above.  We need to do our best at searching and cleanup/validate the user's input.

**Comment by amolsontakke3576** [comment]
@dealako For some special characters like `+` backend endcoding does not work so we need to add `encodeURIComponent` from frontend site before calling search organization endpoint.

**Comment by rinkeshbhutwala** [comment]
@nirupamav For **Landis+Gyr North America** company instead of that you need to replace **+** to **%2b**

**Comment by nirupamav** [comment]
**Tested and observed below issues and hence reopening the ticket**
**Endpoint https://api.dev.lfcla.com/v3/api-docs#operation/searchCompany**

**_1. 422 is returned when trying to search with special characters. The company names I tried to search is already existing in org service and I am able to query them in org service endpoint. _**
```
Values tested
Famous Dave's of America, Inc.
StackEngine (now owned by Oracle)
```
**cla-service**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6c749691-a205-420a-98f8-6c739976e8b0)

**org-service**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/eb6239af-fa86-4345-848a-df2f4f11561e)



```
Issue2 is working fine
Issue3 searching with special characters is being tracked in https://jira.linuxfoundation.org/browse/PMM-657. Based on the feedback from org-service will check if we need to encode or directly use the special characters
```

**Comment by rinkeshbhutwala** [comment]
@nirupamav searching with special characters gives swagger error so we need to finalize the pattern for which special characters need to allow.
@dealako Can you please confirm once so we can update the swagger pattern which allows special characters or should we just remove the pattern from search endpoint?

**Comment by rinkeshbhutwala** [comment]
@dealako Have you finalize the swagger pattern with @pranab-bajpai  which allows special characters or should we just remove the pattern from search endpoint?

**Comment by dealako** [comment]
@amolsontakke3576 has indicated that we are using the same regex as provided by the Organization Service. We will use this regex going forward as this is what is supported by SalesForce. Closing this ticket now.
