### ISSUE TITLE
Individual Contributor Console Flow Integration - CCLA - With No Signed CLA

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1198]
## Summary

Integrate the Individual Contributor Console Flow Without a Signed CLA flow with the backend API.

## Background

David has documented the API flows that the existing v1 system uses and "should work" with the Contributor Console CCLA - Without a Signed CLA flow. See the [PRD](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table3.ContributorConsoleIndividualCLAflowwhenthereisnosignedCLAbutthecompanyisthere.) - Table 3

## User Story

As a contributor, I want to sign a CCLA for my project on behalf of my company.

## Tasks

- [ ] Build and Integrate a new EasyCLA v1 API that determines if the user has an auth0 account and we're able to find it from their GH info - (PRD Table 3, Step 3)
- [ ] Build and Integrate a new EasyCLA v1 API that promotes SFDC User (from a Lead to Contact) - (PRD Table 3, Step 3)
- [ ] Build and Integrate a new EasyCLA v1 API that assigns the current user a new role of CLA Designee - (PRD Table 3, Step 3)
- [ ] Integrate into the v2 Contributor Console

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by wanyaland** [comment]
@dealako .. On checking this flow.. Its quite similar to #1107 and am assuming this can be leveraged here

**Comment by dealako** [comment]
Task moved to next sprint.

**Comment by nirupamav** [comment]
@wanyaland 
Is this ticket only for API and as per your comment above is the endpoint same as in #1107? If not can you provide the endpoint to test this ticket

**Comment by wanyaland** [comment]
@nirupamav its not the same actually as flow is similar but some caveats. The API-DOCs for this is https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/inviteCompanyAdmin

**Comment by nirupamav** [comment]
@wanyaland 
Since name field will be added to the UI, this endpoint might need changes and hence reopening the ticket

**Comment by wanyaland** [comment]
@nirupamav . Name issue was resolved in #1361

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**1. companyID ia accepting internal ID from CLA database. Shoudln't it accept the sales force ID of the company**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/17034cef-21e2-49e0-bc68-44a36d2b79d2)
**2. Able to send cla-manager-designee request or contact admin for already signed project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/50b01c56-a20b-49e5-9d47-9cb2aa0392a7)
**3. Issues with email notification sent to user to created LFID is tracked in ticket #1549**
**4. name field is not accepting numbers. Is this as per requirement. As per discussion in https://jira.linuxfoundation.org/browse/LFX-1914 name field should accept /^[a-z][a-z0-9.]+[a-z0-9]$/**
**5.** Appropriate error message is not displayed when cla-manager-designee request is sent multiple times for the same user who does not have LFID
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8bb7d44b-f678-4efb-8aea-c9b4f0d000e7)
**6. Appropriate error message is not displayed when no value is passed for name field or when name field is missing in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e72386cf-3379-4526-8e32-1f152c511d6a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ccf19f75-ed2f-4b99-bd86-98ee7b4d3791)

**7. Appropriate error message is not displayed when no value is provided for claGroupID or when claGroupID is missing in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9165f98e-447f-4f1b-9ecb-8b350ed20ed3)

**8. Appropriate error message is not displayed when value is not passed for userEmail field or when userEmail field is missing in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0dc42dd1-72be-4f82-8b8b-1fa3db6934f3)

**9. userEmail accepts invalid email format for e.g. nirupamav@test**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/12dd2ed9-d69a-4b0f-9320-ca5d07bc0d67)

**10. Able to send cla-manager-request even when invalid userid is provided in the endpoint url**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/206db36a-199c-42f4-9bc2-2688c1a5c086)

**Comment by wanyaland** [comment]
@nirupamav 
Issue 1- The internal ID is used since this is at contributor level and not LFX end . This is easier for one on the frontend to use this with claGroup IDs.

**Comment by nirupamav** [comment]
**_Tested and observed that below issues are still reproducible and observed a new isse_**

**2. Able to send cla-manager-designee request or contact admin for already signed project. Issue is fixed only for user with LFID but still able to send request to user without LFID**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d40f8119-9bce-4183-922b-330de72a83bc)

**7. 500 internal server error is displayed when claGroupID is missing or when value is not provided to claGroupID or when invalid claGroupID is provided in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1f48908d-32bd-4000-82f9-764496dc72b8)

**8. Appropriate error message is not displayed when value is not passed for userEmail field or when userEmail field is missing in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0f3f8eb8-99db-4a7d-93ba-d4fa28ccf000)

**10. Able to send cla-manager-request even when invalid userid is provided in the endpoint url**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7e4abeb8-1d1d-4e92-a9d8-3f068f74f133)

**11. Able to send request when name field is empty or when name field is missing in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/07783fe5-101b-446d-a95a-0020637bd487)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e247a252-7092-4000-a308-ab57d7460d99)

**Comment by dealako** [comment]
@rinkeshbhutwala - please address #7 for us.  Respond with the appropriate error message.

**Comment by nirupamav** [comment]
All issues are fixed except Issue2. Logged ticket #2043 to track the issue and closing this ticket
