### ISSUE TITLE
Staging - Event Log Write Error

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1594]
## Summary

Staging - Event Log Write Error is preventing event log entries from being written in STAGING.

## Background

Error is:

```
time="2020-08-17T09:10:24Z" level=warning msg="Unable to create a new event,
error: ValidationException: One or more parameter values were invalid: Type
mismatch for Index Key event_date_and_contains_pii Expected: B Actual: S
IndexName: event-date-and-contains-pii-event-time-epoch-index\n\tstatus code:
400, request id: ACUKTJLHUPA2Q77BEVBU8917OVVV4KQNSO5AEMVJF66Q9ASUAAJG"
```

It appears we are trying to set the wrong type on the PII field (should be boolean, not string).

## Tasks

- [ ] Identify the cause of the issue - why is this occurring in STAGING and not DEV?  Was this previously fixed and not pushed to STAGING yet?
- [ ] Implement the solution/fix.
- [ ] Coordinate with Sudhakar to confirm fix as he observed and reported this issue - see LFX ticket below

## Expected behavior

Event logs should be added to the events table.

## Screenshots

No events since March (although we don't test often here):

![Screen Shot 2020-08-17 at 11.40.06 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/89ac59b4-73ef-40d1-a4c8-98c5233732e6)

## Environment

* Environment: STAGING 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [Event Log Error in CloudWatch](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcla-backend-go-api/log-events/2020$252F08$252F17$252F$255B$2524LATEST$255D837871cdf4d24bfeb9f8ae4db32a5959$3Fstart$3D2020-08-17T09$253A10$253A24.503Z)
- [LFX-2271 Issue](https://jira.linuxfoundation.org/browse/LFX-2271)

**Comment by rinkeshbhutwala** [comment]
@dealako In **DEV** we have filed type is a **string**
{
        "AttributeName": "event_date_and_contains_pii",
        "AttributeType": "**S**"
}

And for STAGING and PROD, we have field type is bool
{
        "AttributeName": "event_date_and_contains_pii",
        "AttributeType": "**B**"
}


because of that event is failed.

**Comment by dealako** [comment]
@nirupamav @rinkeshbhutwala  We have merged the index and data updates to STAGING and PROD.  Ready for test.

**Comment by nirupamav** [comment]
As per discussion with Rinkesh, issue still exists and hence moving the ticket to InDev status

**Comment by rinkeshbhutwala** [comment]
@dealako I have tested today again still I am getting the same issue it shows me **event_date_and_contains_pii** as **Bool** value instead of the **string**

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam I have tested and reviewed this ticket and looks like the issue is fixed so moved this ticket to Ready For QA.

**Comment by dealako** [comment]
This issue is resolved after DB schema update.
