### ISSUE TITLE
Add Optional Watermark to PDF

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1621]
## Summary

Add Optional Watermark to PDF

## Background

A stakeholder has requested that we add a watermark on our preview PDFs to indicate that they should NOT sign (via pen and ink). In this use case, contributors would want to download the PDF and share it with their legal department for approval. Once approved, the contributor could use our tool to sign the document via DocuSign. To support this, and to avoid confusion, we should add a "Not for Execution" watermark to the PDF prior to streaming the template back to the user for UI display and download.

- [Example of what the PDF should look like (watermark example)](https://app.zenhub.com/files/194341141/9ae15d46-1e23-4049-82a1-95a2838eea93/download)

## Tasks

- [x] Review ticket #1604 - which describes how to identify the ICLA and CCLA for a given CLA Group.
- [x] Create a new API endpoint for fetching a given template for a CLA Group. Inputs are CLA Group and `cla_ type`: `icla` or `ccla`.  Add an optional watermark flag to the query as we may want to use this API for non-watermark use-cases. Normally the UI can directly download the template since it's public read-only, but in this case, we need an API/logic to overlay the watermark. 
- [x] Investigate [this PDF library](https://github.com/unidoc/unipdf) [with examples](https://unidoc.io/examples/image/watermark-pdf) (example [repo here](https://github.com/unidoc/unipdf-examples)) to see if we can easily add the watermark to existing PDF documents.  This library appears to require a license fee.
- [x] If possible, identify an open-source library that can do this.  We can ask around the community to see if anyone can recommend a library if a search comes up empty.
- [x] Determine if we should:
  - add the watermark on-the-fly. This is the best option and would easily solve all use-cases. Simple case.
  - add the watermark when we generate the template - save a version without the watermark for DocuSign and a version with the watermark for preview/download.  Note: for non-Apache templates, we have a manual upload process (not auto-generated). We get @WillsonHG or developer to manually add existing PDFs to the S3 bucket. In this case, we would need to post-process the uploaded PDFs to make a version of the PDF with the watermark.  More complex.

Gotchas:
- [x] need to add /v4 path pass through in the API-GW (no LF Login required) - may want to add Google Auth check?
- [x] ideally, do not write/read from disk - do everything in-memory if possible
- [x] we've had trouble with the API properly setting the mime/application type. Data was, by default, base64 encoded (no reason to base64 encode a PDF document).

## User Story

- As a contributor, I want to download the ICLA or CCLA template and share it with my legal team.
- As a project manager, I want contributors to download a copy of the ICLA or CCLA template with a watermark to indicate that they should not sign with a pen, but use the EasyCLA tool to execute/sign the document.

## Assumptions

- The library referenced above can add watermark as described
- The watermark library can update all pages in the document

## Questions

List any questions or clarifications that are needed to addressed to satisfy this request.

1. N/A
1. N/A

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- See above links.

**Comment by makkalot** [comment]
For now we'll go with this open source library instead of the payed one : https://github.com/pdfcpu/pdfcpu

**Comment by nirupamav** [comment]
**Verified that the issue is fixed. Attaching the document for reference**
[https://app.zenhub.com/files/194341141/9e8c3074-d3de-4d6e-a039-2ff84fe17275/download](https://app.zenhub.com/files/194341141/9e8c3074-d3de-4d6e-a039-2ff84fe17275/download)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9463ab4a-34b7-4b9c-ab7c-d26634e4fb1a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/889c6cab-afa3-42c9-9e6a-b18b2c96646c)
