### ISSUE TITLE
Event Log Message Simplification

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1648]
## Summary

The event log text shared with users is too complex - add simplified text for showing user from the UI.

## Background

The event log text includes a bunch of technical and non-technical information about the specific event. Users in the UI are interested in only a quick summary of the event information.

This task is to adjust the event log to include both detailed and summary information.  Both the summary and detailed information will be included in the API response model - the UI can show the summary information in a table view and optionally show the details (mouse over, pop-up window, or whatever) when the user drills down into the information.

## Tasks

- [ ] [Review the existing data model and pattern](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/event_data.go) for the event log schema. Notice we have a [single function for this primary interface](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/event_data.go#L13).
- [ ] [Modify the interface ](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/event_data.go#L13) to include two function similar to: summary and details - ideally, rename existing to be `GetEventDetailsString` and add a new function for `GetEventSummaryString`
- [ ] [Review the existing functions](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/event_data.go#L258-L540) - update to set both details and summary information (work with David on how Summary 
- [ ] Add an additional column [to the data model](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/models.go#L22): `summary` as well as [here](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/models.go#L51).
- [ ] Add [additional argument](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/repository.go#L113) to the create event and update the response model to return the summary.  Don't forget the [projection updates](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/repository.go#L525).
- [ ] [Review](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L1785) and [Update the swagger spec](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/common/event.yaml#L41) to include a summary field.
- [ ] we will need to review and possibly update the code where we call the create event logic - need to confirm
 
## User Story

As a project manager, I want to see a summary and detailed view of the events from the LFX Portal.

## Assumptions

- No indexes need to be adjusted/created/update.
- We will not update existing event records in DEV, STAGING or PROD.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
**_Tested and observed that Event summary is not available for below events. I was not able to test few more events due to bugs in those flows. When the bugs are resolved and if I find issue with the events will log separate ticket_**

**1.  When CLA is signed for organization**
```
 {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "corporate signature signed for project ProjectLevelChild1MoreThan1SubProject and company CLA Test Organization by user clatestuser five",
            "EventFoundationSFID": "a091700000AHpttAAD",
            "EventID": "9ad64403-5e90-4524-8900-8557a8b95a3f",
            "EventProjectExternalID": "a091700000AHpttAAD",
            "EventProjectID": "b256b588-f6d9-4c72-9d3b-1ac157217640",
            "EventProjectName": "ProjectLevelChild1MoreThan1SubProject",
            "EventProjectSFID": "a091700000AHptyAAD",
            "EventProjectSFName": "ProjectLevelChild1MoreThan1SubProject",
            "EventTime": "2020-08-28T09:35:53.723464+0000",
            "EventTimeEpoch": 1598607353,
            "EventType": "CompanySignatureSigned",
            "UserID": "9e0970b7-d8be-11ea-91a4-722b5a05dd3e",
            "UserName": "clatestuser five"
        },
```
**2. When corporate contributor is acknowledged**
```
{
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "employee signature created for user clacontributor2 test, company CLA Test Organization, project ProjectLevelChild1MoreThan1SubProject",
            "EventFoundationSFID": "a091700000AHpttAAD",
            "EventID": "3bdad381-ef14-4de0-aad8-f0722cc30615",
            "EventProjectExternalID": "a091700000AHpttAAD",
            "EventProjectID": "b256b588-f6d9-4c72-9d3b-1ac157217640",
            "EventProjectName": "ProjectLevelChild1MoreThan1SubProject",
            "EventProjectSFID": "a091700000AHptyAAD",
            "EventProjectSFName": "ProjectLevelChild1MoreThan1SubProject",
            "EventTime": "2020-08-28T09:53:56.054045+0000",
            "EventTimeEpoch": 1598608436,
            "EventType": "EmployeeSignatureCreated",
            "UserID": "cb9bc8db-e906-11ea-a54b-ba8a36866079",
            "UserName": "clacontributor2 test"
        },
```
**3. When Individual Contributor signs ICLA**
```
 {
            "EventCompanyName": "undefined",
            "EventData": "individual signature of user clacontributor2 test signed for project ProjectLevelChild1MoreThan1SubProject",
            "EventFoundationSFID": "a091700000AHpttAAD",
            "EventID": "b4d1dd79-b4d9-40eb-aa31-434d8c71c5d3",
            "EventProjectExternalID": "a091700000AHpttAAD",
            "EventProjectID": "b256b588-f6d9-4c72-9d3b-1ac157217640",
            "EventProjectName": "ProjectLevelChild1MoreThan1SubProject",
            "EventProjectSFID": "a091700000AHptyAAD",
            "EventProjectSFName": "ProjectLevelChild1MoreThan1SubProject",
            "EventTime": "2020-08-28T09:53:56.054045+0000",
            "EventTimeEpoch": 1598608436,
            "EventType": "IndividualSignatureSigned",
            "UserID": "cb9bc8db-e906-11ea-a54b-ba8a36866079",
            "UserName": "clacontributor2 test"
        },
```

**Comment by rinkeshbhutwala** [comment]
@dealako I have verified this ticket at some places summary is coming properly and some of the places it's not come up.

Looks likes the create event working flow is not the same in the whole cla-service see if you can help me on this I do not identify from where create events are calling that's why at someplace summary is missing.

**Comment by nirupamav** [comment]
Observed that above mentioned issues are fixed. In case if I find any issues while trying other flows will log separate ticket
```
{
    "Events": [
        {
            "EventCompanyName": "undefined",
            "EventData": "individual signature of user None signed for project FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "0a3c63a5-692f-48de-8ec1-61b3bdd60fd2",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "individual signature of user None signed for project FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T10:07:06.844404+0000",
            "EventTimeEpoch": 1599127626,
            "EventType": "IndividualSignatureSigned",
            "UserID": "79c0722b-356e-4f30-8ef8-f373a99392ff"
        },
        {
            "EventCompanyID": "8236f284-f76e-4e32-aa6d-adc44efda053",
            "EventCompanyName": "Proxima Systems",
            "EventCompanySFID": "00117000015zTG8AAM",
            "EventData": "corporate signature signed for project FoundationLevel1subprojectParent and company Proxima Systems by user John Doe",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "7363a083-432a-4185-9c65-7d8f8bfbbc96",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "corporate signature signed for project FoundationLevel1subprojectParent and company Proxima Systems by user John Doe",
            "EventTime": "2020-09-03T10:07:06.844404+0000",
            "EventTimeEpoch": 1599127626,
            "EventType": "CompanySignatureSigned",
            "UserID": "b9cdfea9-c296-11ea-b64f-16f8618820d9",
            "UserName": "John Doe"
        },
        {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "employee signature created for user Nirupamav Pinky, company CLA Test Organization, project FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "29bbf298-c41e-4556-9452-1b0e2d0e0401",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "employee signature created for user Nirupamav Pinky, company CLA Test Organization, project FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:36:15.873977+0000",
            "EventTimeEpoch": 1599118575,
            "EventType": "EmployeeSignatureCreated",
            "UserID": "b523f8e4-d7fd-4ff7-8509-a3803fa1fecd",
            "UserName": "Nirupamav Pinky"
        },
        {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "user Nirupamav Pinky/nirupamavpink/62586327/b523f8e4-d7fd-4ff7-8509-a3803fa1fecd associated with company CLA Test Organization for project FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "25959b07-9d30-45e4-b285-14408e9b58cf",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "user Nirupamav Pinky/nirupamavpink/62586327/b523f8e4-d7fd-4ff7-8509-a3803fa1fecd associated with company CLA Test Organization for project FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:36:15.873977+0000",
            "EventTimeEpoch": 1599118575,
            "EventType": "UserAssociatedWithCompany",
            "UserID": "b523f8e4-d7fd-4ff7-8509-a3803fa1fecd",
            "UserName": "Nirupamav Pinky"
        },
        {
            "EventCompanyName": "undefined",
            "EventData": "individual signature of user Nirupamav Pinky signed for project FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "57ca6a86-5008-4dc1-954f-fa85d9c91f85",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "individual signature of user Nirupamav Pinky signed for project FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:36:15.873977+0000",
            "EventTimeEpoch": 1599118575,
            "EventType": "IndividualSignatureSigned",
            "UserID": "b523f8e4-d7fd-4ff7-8509-a3803fa1fecd",
            "UserName": "Nirupamav Pinky"
        },
        {
            "EventData": "user [clatestuser pm2] added github repository [pc-openmainframe-ade/pc-itx] to project [FoundationLevel1subprojectParent]",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "4934082e-745a-4a4c-b1fd-27eed20afd31",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "user clatestuser pm2 added github repository pc-openmainframe-ade/pc-itx to project FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:21:16Z",
            "EventTimeEpoch": 1599117676,
            "EventType": "repository.added",
            "LfUsername": "clatestuserpm2",
            "UserID": "84006986-daf8-11ea-8786-3e13ab5f8b06",
            "UserName": "clatestuser pm2"
        },
        {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "CLA Manager [clatestuser5 / nirupamav+clatestuser5@proximabiz.com / 562b834d-ec7b-11ea-ba0e-2205c6514c5d] added Domain proximabiz.com to the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "aeee435d-6254-4542-8a5e-aac0457544e9",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "CLA Manager clatestuser5 added Domain proximabiz.com to the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:14:38Z",
            "EventTimeEpoch": 1599117278,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "clatestuser5",
            "UserID": "562b834d-ec7b-11ea-ba0e-2205c6514c5d",
            "UserName": "clatestuser five"
        },
        {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "CLA Manager [clatestuser5 / nirupamav+clatestuser5@proximabiz.com / 562b834d-ec7b-11ea-ba0e-2205c6514c5d] removed Email test@test.com from the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "ca9aa3d8-fe8a-4cd8-a95d-6abccbeb39d1",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "CLA Manager clatestuser5 removed Email test@test.com from the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:13:49Z",
            "EventTimeEpoch": 1599117229,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "clatestuser5",
            "UserID": "562b834d-ec7b-11ea-ba0e-2205c6514c5d",
            "UserName": "clatestuser five"
        },
        {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "CLA Manager [clatestuser5 / nirupamav+clatestuser5@proximabiz.com / 562b834d-ec7b-11ea-ba0e-2205c6514c5d] removed GitHub Org test from the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "d53d0ef2-5f4c-4866-a104-0290108ab1e3",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "CLA Manager clatestuser5 removed GitHub Org test from the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:13:49Z",
            "EventTimeEpoch": 1599117229,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "clatestuser5",
            "UserID": "562b834d-ec7b-11ea-ba0e-2205c6514c5d",
            "UserName": "clatestuser five"
        },
        {
            "EventCompanyID": "c83ef624-c370-4a70-80e4-5e70f35aac7e",
            "EventCompanyName": "CLA Test Organization",
            "EventCompanySFID": "00117000018BhtKAAS",
            "EventData": "CLA Manager [clatestuser5 / nirupamav+clatestuser5@proximabiz.com / 562b834d-ec7b-11ea-ba0e-2205c6514c5d] removed Domain test.com from the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventFoundationSFID": "a091700000ARkg7AAD",
            "EventID": "f74f4f1e-212c-48dc-8aa6-72a3acbbfa74",
            "EventProjectExternalID": "a091700000ARkg7AAD",
            "EventProjectID": "bd66f403-d6d0-4266-836b-0ece7eac029e",
            "EventProjectName": "FoundationLevel1subprojectParent",
            "EventProjectSFID": "a091700000ARkg7AAD",
            "EventProjectSFName": "FoundationLevel1subprojectParent",
            "EventSummary": "CLA Manager clatestuser5 removed Domain test.com from the approval list for Company: CLA Test Organization, Project: FoundationLevel1subprojectParent",
            "EventTime": "2020-09-03T07:13:49Z",
            "EventTimeEpoch": 1599117229,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "clatestuser5",
            "UserID": "562b834d-ec7b-11ea-ba0e-2205c6514c5d",
            "UserName": "clatestuser five"
        }
    ],
    "NextKey": "eyJldmVudF9mb3VuZGF0aW9uX3NmaWQiOnsiQiI6bnVsbCwiQk9PTCI6bnVsbCwiQlMiOm51bGwsIkwiOm51bGwsIk0iOm51bGwsIk4iOm51bGwsIk5TIjpudWxsLCJOVUxMIjpudWxsLCJTIjoiYTA5MTcwMDAwMEFSa2c3QUFEIiwiU1MiOm51bGx9LCJldmVudF9pZCI6eyJCIjpudWxsLCJCT09MIjpudWxsLCJCUyI6bnVsbCwiTCI6bnVsbCwiTSI6bnVsbCwiTiI6bnVsbCwiTlMiOm51bGwsIk5VTEwiOm51bGwsIlMiOiJmNzRmNGYxZS0yMTJjLTQ4ZGMtOGFhNi03MmEzYWNiYmZhNzQiLCJTUyI6bnVsbH0sImV2ZW50X3RpbWVfZXBvY2giOnsiQiI6bnVsbCwiQk9PTCI6bnVsbCwiQlMiOm51bGwsIkwiOm51bGwsIk0iOm51bGwsIk4iOiIxNTk5MTE3MjI5IiwiTlMiOm51bGwsIk5VTEwiOm51bGwsIlMiOm51bGwsIlNTIjpudWxsfX0="
}
```
