### ISSUE TITLE
Project Console - CCLA and ICLA PDF Date Not Correct

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1872]
## Summary

Project Console - CCLA and ICLA PDF Date Not Correct

## Background

When we have multiple ICLA and/or CCLA documents, the latest PDF should show the correct date - not the date of the first PDF document.

## Tasks

Sort Order
- [ ] Check the Major Version First - latest version should be the selected version, if a tie, then check next criteria
- [ ] Check the Minor Version Second - lastest version should be the selected version if a tie, then check next criteria
- [ ] Check the Date third - lastest date should be selected
- [ ] Other entries should be in date descending order

For example:
- Here is how the python side [decides the latest template](https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py#L1119-L1147)

## Screenshots

![Screen Shot 2020-09-25 at 11.55.49 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/a81dedfe-e138-49a8-b686-e6ee9a20864f)

![Screen Shot 2020-09-25 at 11.55.55 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/b61711df-b2fc-4f78-824c-bc56e21bb74b)

## Environment

Please complete the following information:

* Environment: DEV, STAGING and PROD 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
How to test/validate:

1. Create a new CLA Group with both CCLA and ICLA, note the Project Name, Entity Name, and email address
1. Upon completion and possible page refresh, observe the dates/times are correct on the project console for the New CLA Group
1. Observe the dates are correct in the ICLA PDF Icon -> Modal pop-up. Observe that there is one PDF for ICLA.
1. Observe the dates are correct in the CCLA PDF Icon -> Modal pop-up. Observe that there is one PDF for CCLA.
1. Find CLA Group in the EasyCLA database - cla-dev-projects
1. Observe that there is one element in the project_individual_documents field and one element is in the project_corporate_documents field.
1. Navigate to AWS S3 DEV - cla-signature-files-dev bucket, path: cla-signature-files-dev/contract-group/{cla_group_id}/template - observe icla and ccla files are in S3 - files have the following format: icla-YYYY-MM-DDTHH-MM-SSZ.pdf and ccla-YYYY-MM-DDTHH-MM-SSZ.pdf format
1. Identify the CLA Group again in the Project console
1. Press the Select Template button, Select Apache Style Template
1. Enter new values, note values you entered, use different values from the previous attempts
1. Generate new templates
1. Upon completion and possible page refresh, observe the dates/times are correct on the project console for the New CLA Group
1. Observe the dates are correct in the ICLA PDF Icon -> Modal pop-up. Observe that there are two PDFs for ICLA. Ensure most recent PDF is first and selected.
1. Observe the dates are correct in the CCLA PDF Icon -> Modal pop-up. Observe that there are two PDFs for CCLA.  Ensure most recent PDF is first and selected.
1. Find CLA Group in the EasyCLA database - cla-dev-projects - may require a new search to "see" updated values.
1. Observe that there are two elements in the project_individual_documents field and two elements are in the project_corporate_documents field.  The first element is the first one added, the second element is the most recent/latest one added.
1. Navigate to AWS S3 DEV - cla-signature-files-dev bucket, path: cla-signature-files-dev/contract-group/{cla_group_id}/template - observe that two icla and two ccla files are in S3 - files have the following format: icla-YYYY-MM-DDTHH-MM-SSZ.pdf and ccla-YYYY-MM-DDTHH-MM-SSZ.pdf format

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
