### ISSUE TITLE
Identify Steps to Prevent Direct Default Branch Commits

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1912]
## Summary

Identify Steps to Prevent Direct Default Branch Commits

## Background

As part of the stakeholder review, we need to confirm if setting up Branch Protection will indeed prevent users from committing directly to the default (master) branch.

## Tasks

- [ ] Does the current branch protection feature prevent users from committing to the default (master) branch?
- [ ] If not, Identify steps to prevent users from committing to the default (master) branch
- [ ] If not, review current branch protection logic and develop a plan for incorporating protections for committing to the default (master) branch

## User Story

As a legal representative, I want to confirm that by enabling branch protection on a given repository will prevent users from committing directly to the default (master) branch.

## Assumptions

- EasyCLA bot has Admin permissions

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by makkalot** [comment]
did couple of tests and I think our current solution protects the branch even if the person who is the one trying to bypass the checks forcefully is administrator.

### some of the tests being run : 

- **check with admin → true**
    - if can push -u work :
![Screenshot_2020-10-06_at_16.18.06.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/02fb7620-e0e1-4b63-8b16-d14aa8afa44b)
    - if can push -f can work :
![Screenshot_2020-10-06_at_16.18.30.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/60acf927-b740-49e6-bc18-5911c8d04f43)

- **check if admin → false**
    - if can push -u and -f work :
![Screenshot_2020-10-06_at_16.23.47.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/fec03823-b767-4f20-8f90-809053384e67)

- **check with allow force pushes**
    - if can push -u work :
![Screenshot_2020-10-06_at_16.26.10.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/2e21b71a-3459-42d8-8043-67eb06d6b6f3)
    - if can push -f can work :
![Screenshot_2020-10-06_at_16.26.17.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/49f61149-bfa6-4151-857b-493197e1578e)



Also found some people trying to bypass those checks for various reasons not being possible, other than calling github api and overriding the commit status : https://github.community/t/pushing-to-a-protected-branch-with-required-status-checks/931

**Comment by dealako** [comment]
The research and notes above the requirements for this ticket. Closing this ticket.
