### ISSUE TITLE
EasyCLA System Email - Send Email When Branch Protection is Adjusted/Disabled from GH Admin

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1915]
## Summary

EasyCLA System Email - Send Email When Branch Protection is Adjusted/Disabled from GH Admin

## Background

The stakeholders want the EasyCLA system to send an email to the Project Managers when a GitHub Organization Owner/Admin adjusts or disables the branch protection settings on a given repository.

## Tasks

- [ ] Identify if the EasyCLA bot can register for callbacks when GH Admins adjust the branch protection security posture
- [ ] If so, update the EasyCLA callback code to handle branch protection associated events. If the changes impact the branch protection security posture, send an email to the Project Managers informing them of the changes.

## User Story

As an EasyCLA Project Manager, I want the EasyCLA system to notify me when the branch protection settings are modified on my repository.

## Assumptions

- [] The EasyCLA GitHub bot can notify the EasyCLA system when GH admins make changes to the branch protection settings.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
We are unable to trap for the appropriate events from GitHub at this time - the events are not sent.
