### ISSUE TITLE
Investigate and Resolve Project Service High Usage

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1939]
## Summary

Investigate and Resolve Project Service High Usage

## Background

One of the EasyCLA services is calling the project service more than expected. This is resulting in extremely high usage, 1+ million requests per day.  This appears to be related to a CRON job we are running for pre-calculating metrics.

Most of the reported API requests are for GET /project-service/v1/projects/{project_sfid}

## Tasks

- [ ] Identify, diagnose, and document in this ticket the Project Service high-usage logic.
- [ ] Review the offending code. Devise a plan of action to reduce the rate at which we query the project service API.
- [ ] Implement API optimizations that will reduce the number of API queries.

## Screen Shots

![image.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/613ee30b-0172-4948-bc09-810c9db16fbd)

## Expected behavior

EasyCLA should not make excessive API calls to the project service.

## Environment

Please complete the following information:

- Environment: DEV, STAGING, and PROD 

## Additional Context

- Reported by @niravpatel27 and Prabodh Chaudhari

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Log insights report from Onkar Kathane:

[https://app.zenhub.com/files/194341141/05aee5c4-1d3d-4d39-aa19-1399b6a66090/download](https://app.zenhub.com/files/194341141/05aee5c4-1d3d-4d39-aa19-1399b6a66090/download)

**Comment by nirupamav** [comment]
@dealako @rinkeshbhutwala
Below is the update from Onkar
As compare to the previous count, now its very low, previously we are getting 150k  request every hr, but now its 250 request we are getting.
But now also cla hitting project service in every hr.
![image](https://user-images.githubusercontent.com/60865903/95953981-47b54c80-0e18-11eb-844b-cf0aa722b2bb.png)

**Comment by dealako** [comment]
This is fine for now and acceptable.
