### ISSUE TITLE
Add Timestamp for Approval List Attributes/Entries

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1947]
## Summary

Add Timestamp for Approval List Attributes/Entries

## Background

The current signature data model/schema does not provide a way to store when a particular entry to one of the four approval lists (email, domain, GH ID, GH Org) is added/updated/modified.  The v2 design calls for identifying

1. who added/updated the approval list entry (which CLA Manager - store lfid and/or user id/user SF id performed the action)
1. when the CLA Manager added/updated the approval list (added/modified date/time)

## Task

- [ ] Update/Enhance the signature approval list elements to include the CLA Manager who performed the added/updated action on the approval list entry
- [ ] Update/Enhance the signature approval list elements to include the date/time of the added/updated action on the approval list entry
- [ ] Ensure these changes are backwards compatible with the existing signature records (e.g. may not be feasible to change the email string list into a complex structure due to backwards compatibility issues, but we would want to favor adding a new column to the record)

## User Story

- As a project manager, I want to know who and when the approval list was modified when I view the approval lists in the Admin console.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.
