### ISSUE TITLE
Infra: FINOS New Template Configuration

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1961]
## Summary

FINOS New Template Configuration

## Background

Per stakeholder discussion on 10/07/2020, Steve Winslow (LF Legal) indicated that a new CLA CCLA and ICLA template would be provided prior to FINOS going live in PROD.  This task is to track activities of configuring the production system with the new templates.

## Tasks

- [x] Acquire the FINOS ICLA and CCLA templates from the LF Legal team
- [x] Upload the FINOS ICLA and CCLA templates to the PROD S3 templates bucket. Ensure the templates have public-read access (no write)
- [x] Create the FINOS CLA Group in PROD if not already created - use the Apache Style Template as a template placeholder
- [x] Identify the CLA Group in the `cla-projects-prod` table and review the Individual and Corporate document settings:
    - Adjust the template name, version, and URL to desired/appropriate values
    - Adjust the X and Y coordinates to match the PDF template input fields
- [x] Test and validate the template settings and input field values

## User Story

- As a project manager, I want to leverage the updated FINOS ICLA and CCLA templates prior to going live in PROD.

## Assumptions

- Both ICLA and CCLAs will be provided to the onboarding team

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Both ICLA and CCLA templates are active in PROD
1. Execute an ICLA and CCLA DocuSign flow to ensure input field alignment

## References

- N/A

**Comment by dealako** [comment]
Blocked - waiting on the templates from LF legal.

**Comment by WillsonHG** [comment]
this has been completed and is in prod.
