### ISSUE TITLE
Use GitHub User's Primary Email When Preparing DocuSign

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1962]
## Summary

Use GitHub User's Primary Email When Preparing DocuSign

## Background

Brian Warner suggested that we should detect and use a GitHub contributor's primary GitHub email address when executing the ICLA DocuSign flow.  It was observed that his secondary email address was used to pre-set the ICLA Document within DocuSign.

## Expected behavior

- User's Primary GitHub email address is used to pre-set the ICLA Document within DocuSign

## Tasks

- [ ] Investigate if we can determine the user's primary GitHub email address
- [ ] If so, select the primary GitHub email address when preparing the DocuSign flow
- [ ] Test, validate, and demonstrate that the primary GitHub email address is indeed used.

## Screenshots

- N/A

## Environment

Please complete the following information:

* Environment:
  - [ ] DEV
  - [ ] STAGING
  - [X ] PROD 
* Browser:
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.35

## Additional Context

- User has primary and alternate email addresses configured in GitHub.

## Assumptions

If you are assuming certain facts or scenarios, list them so we have a baseline to understand your request.

- N/A

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- N/A

**Comment by brianwarner** [comment]
Looks accurate to me, although it might be useful to simply present a dropdown with the options on that first page that tells you to hang out while the docusign is being generated. There may be edge cases where a user would want to use a non-primary email as well. This functionality is already in the corporate CLA flow, so hopefully it might be possible to bring it over?

**Comment by nirupamav** [comment]
Testing Blocked due to #2032

**Comment by nirupamav** [comment]
Testing blocked due to #2079

**Comment by nirupamav** [comment]
@dealako @makkalot 
Verified that primary email is displayed in docusign. However there is no drop down to select email. Will this be implemented?
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c1870551-26a6-44e9-9797-c4e03102f7fa)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/78a8eb4c-8ccb-4f03-a1bd-ef8857ffd93c)

**Comment by makkalot** [comment]
The feature requires `github_oauth2_token` so we can do a lookup for it via github api. Somehow we need that value being passed via the frontend otherwise there's no way we can connect and get that info from github api.

**Comment by brianwarner** [comment]
I think I mentioned this in the meeting, but it should not be the primary email. It should present a list of the emails associated with the account.

**Comment by brianwarner** [comment]
This already happens in the corporate flow, this behavior should just match that.

**Comment by vinod-kadam** [comment]
Denise to discuss with Amol on whether front end can pass primary email token.

**Comment by brianwarner** [comment]
Please, let me say this again more clearly: *do not try to guess the primary email*. Present all of the emails in a list and let the user tell us their chosen email.

**Comment by mlehotsky** [comment]
sounds good
