### ISSUE TITLE
UI - Update EasyCLA to Use Common LFX Footer

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2097]
## Summary

UI - Update EasyCLA to Use Common LFX Footer

## Background

https://github.com/LF-Engineering/lfx-header#lfxfooter-2

```
<script src="https://cdn.dev.platform.linuxfoundation.org/lfx-footer.js"></script>
```

add the <lfx-footer></lfx-footer>  tag in the footer definition.

## Tasks

- [x] Update v1 Project Console footer
- [x] Update v1 Corporate Console footer
- [x] Update v1 Contributor Console footer
- [x] Update v2 Contributor Console footer - work with @pranab-bajpai on the design/placement

## User Story

- As a project manager, I want a common footer across all consoles.

## Acceptance Criteria

- Demonstrate updated footer to stakeholders

## References

- [common footer](https://github.com/LF-Engineering/lfx-header#lfxfooter-2)
- [v1 Project Console footer](https://github.com/communitybridge/easycla/tree/master/cla-frontend-project-console/src/ionic/layout/cla-footer)
- [v1 Corporate Console footer](https://github.com/communitybridge/easycla/tree/master/cla-frontend-corporate-console/src/ionic/layout/cla-footer)
- [v1 Contributor Console footer](https://github.com/communitybridge/easycla/tree/master/cla-frontend-contributor-console/src/ionic/layout)
- [v2 Contributor Console footer](https://github.com/communitybridge/easycla-contributor-console/tree/master/src) - work with @pranab-bajpai  on the design/layout/placement.

**Comment by amolsontakke3576** [comment]
@dealako For older angular version cdn will be
<script src="https://cdn.dev.platform.linuxfoundation.org/lfx-footer-no-zone.js"></script>

**Comment by tejasadg** [comment]
V2 footer PR link https://github.com/communitybridge/easycla-contributor-console/pull/133

**Comment by manishv09** [comment]
Verified and found new footer is updated on all Project, Corporate and Contributor console.
Please find attached screencast for more details.
[https://app.zenhub.com/files/194341141/593fce82-dfee-4c19-ad50-a0951f0bdbf0/download](https://app.zenhub.com/files/194341141/593fce82-dfee-4c19-ad50-a0951f0bdbf0/download)

**Comment by manishv09** [comment]
Contributor Console:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/230c411c-bd85-41ac-8486-8e6b0a69b7cf)
Project:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/24f333a3-e6a2-4de3-9c6d-f4c1c68bda06)

Corporate:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/8925bdcd-c571-49e8-92e6-05a662f22887)
