### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2208]
## Summary

Add a glossary to the EasyCLA v1 and v2 documentation.

## Tasks

Work with @pranab-bajpai to define and add a glossary to the EasyCLA documentation.  Ensure that:

* [ ] EasyCLA Roles are clearly defined, e.g. CLA Manager, CLA Designee, Individual Contributor, Corporate Contributor, PM, etc.
* [ ] Define the consoles - what they are used for
* [ ] What a CLA Group is...
* [ ] what a legal entity is/respresents
* [ ] what a CLA Template is - brief description of how it is used
* [ ] approved list definitions, etc., a brief description of how they are used/managed
* [ ] foundation level cla group defintion

## Acceptance Criteria

1. Documentation changes submitted as a Pull Request
1. Pull Request Reviewed and Approved by Product Owner
1. Presented to stakeholders for review
1. Documentation changes merged to 'master' branch and made public

**Comment by dealako** [comment]
@pranab-bajpai has reviewed and approved.
