### ISSUE TITLE
Add the "ASWF CLA v2.1" template option to the project console for v1 and v2

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2219]
## Summary

We will need to add another template option into the code of EasyCLA to be presented to a project manager in the project console, along with the Apache-Style cla option.

- [x] Heather: In a test scenario, load the templates into a test project to find the correct Docusign alignment values for the fields.
- [x] David: Take the template and values and add these to the code backend for EasyCLA
- [x] Configure the UIs for v1 and v2 to present the new template as an option to select in the project console. 

## Tasks

- [x] Work with @WillsonHG to obtain the ICLA and CCLA templates for ASWF CLA v2.1
- [x] Encode the text for each template into the EasyCLA template repository backend [via this existing pattern](https://github.com/communitybridge/easycla/blob/v1.0.61/cla-backend-go/template/repository.go#L420).
- [x] Work with @WillsonHG on the placement of the user input fields and placement
- [x] Test and Validate HTML to Docraptor PDF generation
- [x] Work with @amolsontakke3576 to ensure the template is made available for the v1 Project Console (should be, by default).
- [x] Test and evaluate with Docusign - verify field tag and offset placement, adjust as necessary to align the values
- [x] Present new template to Pranab, David, and Heather

## Acceptance Criteria

- Demonstrate new template as part of the Project Console template options

## References

- See [existing Apache Style configuration](https://github.com/communitybridge/easycla/blob/v1.0.61/cla-backend-go/template/repository.go#L420).

**Comment by jmertic** [comment]
I believe this correct - it might help to see it in action first to confirm, but what you are describing seems accurate.

**Comment by swinslow** [comment]
Hi @WillsonHG and @jmertic -- adding my two cents:

I am less concerned that this needs to be a template option that is selectable by the user in the project manager console. If that's easy to add with limited effort, then that's great.

I think there are basically two paths we could take:
1. these become another selectable template option in the PM console; OR
2. this is available in the backend and can be set by the EasyCLA team when required for a particular project.

In either case, note that the template versions that John shared will need to be tweaked slightly, to have blank lines rather than the bracketed text in the first few lines.

I'm not sure if my comments here are clear so I'm happy to discuss live at some point if that would be helpful :)

**Comment by jmertic** [comment]
I'm largely in the same pragmatic boat - whatever gets this rolled out soonest as we have projects chomping at the bit to move forward.

**Comment by dealako** [comment]
@makkalot let's work to add this as a second template option to be made available to the PM console. By default, we query for the list of templates in the v1 project console and present the list to the user. If we add the second template, v1 will work as expected. For v2, we will need to incorporate a step where the PM selects which template to use.  I will work with @pranab-bajpai on this.  @WillsonHG has both the ICLA and CCLA templates in a DOC format.

**Comment by WillsonHG** [comment]
@makkalot @swinslow  I removed the bracketed text
[ASWF 2020 CCLA Template v2.1.pdf](https://github.com/communitybridge/easycla/files/5585889/ASWF.2020.CCLA.Template.v2.1.pdf)
[ASWF 2020 ICLA Template v2.1.pdf](https://github.com/communitybridge/easycla/files/5585890/ASWF.2020.ICLA.Template.v2.1.pdf)

John instructed in the ticket that the option be named  'ASWF CLA v2.1'

**Comment by jmertic** [comment]
The naming should be 'ASWF 2020 v2.1'. Otherwise the plan sounds good.

**Comment by WillsonHG** [comment]
Hi @makkalot @dealako  One slight issue here after testing on dev - the cla signatory's name is prefilling and not editable on the document. Meaning that when a cla manager selects "no" to being authorized to sign the cla, and the cla is sent to the signatory they designate - it is using the name the cla manager fills in on the form. This may or may not be the correct name the cla signatory wants to use on a legal document. It should at least be an editable field for the signatory in my opinion.

**Comment by WillsonHG** [comment]
![image](https://user-images.githubusercontent.com/46732999/101100651-e21e4a80-3594-11eb-9666-1b0f9b6c74b2.png)

**Comment by WillsonHG** [comment]
Verified that the signatory name is now editable. This is ready to deploy to prod.

**Comment by WillsonHG** [comment]
This is now in production.
