### ISSUE TITLE
Update info box for CLA Managers approving contributors

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2285]
## Impacted Docs
https://docs.linuxfoundation.org/lfx/easycla/cla-manager/approve-contributors

## Tasks

- [x] The info box at the top that tells a manager they might get an approval request needs to be updated to tell them they still need to add the contributor to their approved list.

- [x] Update the first sentence after the box.

- [x]  Remove the sentence in italics "Multiple CCLA managers cannot authorize/approve the same domain and sign a CCLA for the same company." We do not need that message.

## Verbiage
The info box should read:
"You may receive an email after a contributor sends a request to be added to the Approved list. If you approve them, you should also add their email or GitHub user name to your Approved list."

Since we don't approve by "name" then the first sentence after the info box should say:

"You can approve contributors by adding them to the Approved List."

**Comment by dibyaranjanlf** [comment]
@WillsonHG Updated the document as per your feedback. Please review the content:
https://docs.linuxfoundation.org/lfx/easycla/cla-manager/approve-contributors

**Comment by WillsonHG** [comment]
Just a slight thing for the info box - The beginning -  "You will " should be "You may" since contributors might not send requests in many cases. We don't want managers to assume this will happen in all cases.

**Comment by pranab-bajpai** [comment]
We can rewrite the first sentence replace after with when.
"You will receive an email when a contributor sends a request to be added to the Approved list. If you approve them, you should also add their email or GitHub user name to your Approved list.t"

**Comment by dibyaranjanlf** [comment]
Done! Thanks for your feedback Pranab.

**Comment by WillsonHG** [comment]
Thank you @pranab-bajpai  and @dibyaranjanlf  looks good!
