### ISSUE TITLE
Enable Branch Protection for All Branches

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2432]
## Summary

Configure Branch Protection for All Branches when PM enables branch protection.

## Background

Currently, the Enable Branch Protection attribute on a CLA group establishes branch protection for the "default" branch only.  Per stakeholder feedback, the desired behavior is to enable branch protection for **all branches** on a given set of repositories.  Setting the branch protection rules on all branches ensures that **all contributors** are authorized to contribute code to a given repository.  Furthermore, all subsequent new branches should fall under the same branch protection rules.

## Tasks

- [ ] Update the branch protection logic to be enabled for all branches
- [ ] Update the branch protection logic to ensure all new branches also are branch protected with the same rules
- [ ] Test and validate

## User Story

- As a project manager, I want to enable branch protection on all branches.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Relates to our initial roll-out of branch protection: #1912, #1914, #1667, #1894

**Comment by makkalot** [comment]
@dealako Unfortunately, the wildcard pattern that Github supports via its UI is not supported via their APIs, the main reason from my understanding is because the branch name is part of the URL. As strategy we'd need to go in a loop and enable branch protection for each branch that's present on the repo, also for the new branches we'd need to be handling the events coming from github for newly created branches. 

![Screenshot 2021-01-12 at 15.17.39.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/5ba19f57-c090-4902-a588-8032ec1fc74c)

**Comment by dealako** [comment]
Let's evaluate the GitHub v4 GraphQL API to see if there is an option to set the branch protection wildcard pattern.

**Comment by vinod-kadam** [comment]
This was deployed to DEV & STAGING.

**Comment by manishv09** [comment]
Verified on staging and found working fine. Please refer the attached video's for reference.

[Uploading... BranchProtection-31032021.mp4]

**Comment by manishv09** [comment]
https://images.zenhubusercontent.com/194341141/5059735d-083d-4fac-9d85-6a8387f93be9/brnch_31032021.mp4

**Comment by vinod-kadam** [comment]
This is deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19

**Comment by WillsonHG** [comment]
verified this is working in production
