### ISSUE TITLE
Add Signing Entity Name for Corporate DocuSign Workflows

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2435]
## Summary

Add Signing Entity Name for Corporate DocuSign Workflows

## Background

Per stakeholder feedback, the product should allow the user to create and set a Signed Entity Name and carry the attribute through the various corporate signing agreement workflows.

## Tasks

- [ ] Review [Python routes.py -> request_corporate_signature POST](https://github.com/communitybridge/easycla/blob/main/cla-backend/cla/routes.py#L1225) request payload, add/include a concept of Signing Entity Name `signing_entity_name` field/attribute.
- [ ] review and update [Python signing.py -> request_corporate_signature](https://github.com/communitybridge/easycla/blob/4f13ed1334c2627b2f03ca32b05140f3385effc1/cla-backend/cla/controllers/signing.py#L47) - update as necessary
- [ ] review and update [Python docusign_models.py -> request_corporate_signature](https://github.com/communitybridge/easycla/blob/4f13ed1334c2627b2f03ca32b05140f3385effc1/cla-backend/cla/models/docusign_models.py#L774) - update as necessary
- [ ] review and update [Python docusign_models.py -> handle_signing_new_corporate_signature](https://github.com/communitybridge/easycla/blob/4f13ed1334c2627b2f03ca32b05140f3385effc1/cla-backend/cla/models/docusign_models.py#L704) - update as necessary
- [ ] review and update [Python docusign_models.py -> create_default_company_values](https://github.com/communitybridge/easycla/blob/4f13ed1334c2627b2f03ca32b05140f3385effc1/cla-backend/cla/models/docusign_models.py#L1895) - update as necessary to ensure user's provided company/entity name is set in the DocuSign form
- [ ] Legal entity name should be marked as read-only on the DocuSign form

## User Story

- As a project manager, I want users to specify the proper legal entity name when signing corporate agreements.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

![Organization Name Validation - Page 3.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/bc9d5835-0714-440c-8b6f-3279affa5e05)

![Organization Name Validation - Page 4.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/aa530c05-21fd-45d9-862b-7ef914d4815f)

**Comment by vinod-kadam** [comment]
Corresponding CLA frontend ticket is as follows:
https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2429

**Comment by dealako** [comment]
Merged PR https://github.com/communitybridge/easycla/pull/2442 which includes the initial wave of changes to support the new Signing Entity Name attribute.

**Comment by dealako** [comment]
Merged org service PR to fix typo: https://github.com/LF-Engineering/organization-service/pull/243

**Comment by vinod-kadam** [comment]
This is just the backend ticket - functionality is being QA tested through 2429. So, closing this one.
