### ISSUE TITLE
Add safeguards and logging for template changes v1

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2542]
## Summary

Due to a recent issue in production, we need to make sure we have safeguards, notifications, and logging in place for any changes to a project's template in production. For both v1 and v2

## Background

When a project manager goes into the project console, they have the ability to overwrite the cla template used by the project by selecting the "Select Template" button and generating a new one. It is not made clear to the user that this will overwrite the current template at any time.

## User Story

- As a project manager, I want to understand that selecting a new template will replace the current template. I want to see a gated questions box to make sure I want to perform the action, and then I want to see a confirmation box that it has been changed.

## Tasks

- [ ] If a project already has a cla template enabled, the link should read "Change Template"
- [ ] When the user has made their template selection and clicks "Generate and Review PDFs", this creates the template. The user needs to see a confirmation box that says "Your new template will replace the current template in use by this CLA group. Are you sure you want to proceed?". The user can select either "No. Go Back" or "Yes. I wish to replace the current template." 
- [ ] When the project manager creates a new cla template, an email notice should be sent to the users in the user-permissions table for the project. It should also be sent to the EasyCLA product manager and administrators.
- [ ] An event should be created in the event log that contains the user_id, project_id, and time/date of the template change.

**Comment by WillsonHG** [comment]
@pranab-bajpai  @dealako  This is my idea for making the template changing action clearer in v1. Please review!

**Comment by dealako** [comment]
Won't fix. Out of scope of current product requirements/features.
