### ISSUE TITLE
Invalidate Employee Acknowledgement on Approval List Email or GitHub Username Removal

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2781]
## Summary

Invalidate Employee Acknowledgement on Approval List Email or GitHub Username Removal

## Background

This task is to invalidate the employee corporate acknowledgment when a CLA Manager removes a user's:

- Email from the Approval List
- GitHub Username from the Approval List

## Tasks

- [ ] Review the API logic which removes the approval list entries (both v1 and v2)
- [ ] When the CLA Manager removes one or more `email addresses` from the approval list, invalid the associated employee acknowledgments.  Set approved=false. Add/append a note to the signature record indicating the CLA manager has removed them from the approval list. Ensure an event log is added indicating that the signature record was invalidated.
- [ ] When the CLA Manager removes one or more `GitHub Usernames` from the approval list, invalid the associated employee acknowledgments.  Set approved=false. Add/append a note to the signature record indicating the CLA manager has removed them from the approval list.  Ensure an event log is added indicating that the signature record was invalidated.
- [ ] Test and validate

## User Story

- As a CLA Manager, I want to invalidate an employee's contributor access by removing the user's email or GitHub Username from the Corporate Console

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.
