### ISSUE TITLE
Provide Invalidate Individual CLA API

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2782]
## Summary

Provide Invalidate Individual CLA API.

## Background

The EasyCLA API should provide an API to allow project managers to invalidate existing individual contributors from making contributions.  The API should include an UPDATE API request with the signature ID to invalidate the signature record.  This action will set the approved flag/attribute to FALSE and set a note in the signature note field. Additionally, an event log should record the action.

## User Story

- As a project manager, I want to prevent an individual authorized contributor from making further code contributions. 

## Tasks

- [ ] Develop a v2 swagger API endpoint to allow project managers to invalidate individual contributors. Inputs would be the unique signature ID and be an HTTP PUT request.
- [ ] Developer the API handler which will accept the PUT request and verify permissions (project scope limited to PM/Community Project Managers)
- [ ] Develop the API service layer logic
- [ ] Develop the repository database access layer logic to set the approved flag to false, add/append a note to the `note` column of the record, save the record and make an audit long event with the user's info.
- [ ] Test and validate
- [ ] Notify the product owner that the API is ready for inclusion into the PCC user interface

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Awaiting stakeholder approval.

**Comment by dealako** [comment]
This feature is complete and available in the PCC.
