### ISSUE TITLE
CNCF Migration Summary Report

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2993]
## Summary

Write a python script in easycla-tools to generate a detailed summary report for CNCF

## Background

We have multiple helper scripts in the easycla-tools repository. Many provide a quick summary view. We need a detailed report to confirm the CNCF migration was successful.

## Task

- [ ] Review the scripts generate-cla-groups-report.py and get-cla-signatures-by-project.py as a reference.
- [ ] Script should access a CLA Group ID as input - e.g. CNCF CLA Group ID

For CCLA Report (CSV output file for CCLA)
- [ ] Script should accept a CSV output filename as a command line option for CCLA
- [ ] Query the CLA Group - save the Project Name, Internal ID, External SFID as part of the CSV output
- [ ] For each CCLA record (company CLA signature), output:
       - [ ] Signature ID
       - [ ] Company Name
       - [ ] Company Internal ID
       - [ ] Comapny SFID
       - [ ] CLA Manager info (?) => LFID, Full Name, Email (if possible?)
       - [ ] CLA Manager have IAM access for this Project | Company ?
       - [ ] Approval List - User Email (pipe separator for each item?)
       - [ ] Approval List - Email Domain (pipe separator for each item?)
       - [ ] Approval List - GitHub User Name (pipe separator for each item?)
       - [ ] Approval List - GitHub Organization (pipe separator for each item?)
       - [ ] Date signed
       - [ ] Signed Flag (if signed = false, this means they started, but did not finish, and tried again later)
       - [ ] Approved Flag

For Employee Acks (ECLA) Report (CSV output file for ECLA)
- [ ] Script should accept a CSV output filename as a command line option for ECLA
- [ ] Query the CLA Group - save the Project Name, Internal ID, External SFID as part of the CSV output
- [ ] For each ECLA record (employee CLA signature), output:
       - [ ] Signature ID
       - [ ] Company Name
       - [ ] Company Internal ID
       - [ ] Comapny SFID
       - [ ] User LFID (if present)
       - [ ] User Email (if present)
       - [ ] User Full Name (if present)
       - [ ] User GitHub ID (if present)
       - [ ] Date signed

For Individual CLAs (ICLA) Report (CSV output file for ICLA)
- [ ] Script should accept a CSV output filename as a command line option for ECLA
- [ ] Query the CLA Group - save the Project Name, Internal ID, External SFID as part of the CSV output
- [ ] For each ICLA record (employee CLA signature), output:
       - [ ] Signature ID
       - [ ] User LFID (if present)
       - [ ] User Email (if present)
       - [ ] User Full Name (if present)
       - [ ] User GitHub ID (if present)
       - [ ] Date signed
       - [ ] Signed Flag (if signed = false, this means they started, but did not finish, and tried again later)
       - [ ] Approved Flag

Generate the reports and share with the EasyCLA team, namely Vinod, David, Heather, Denis, etc.

**Comment by vinod-kadam** [comment]
@dealako  I reviewed the reports/fields and they overall look good to me.
however one thought: I think should we add the links to CCLA PDF & ICLA PDF files to the reports?
This will help to identify if there are any CCLA / ICLA PDFs which we have missed to upload.
And secondly, when Heather/QA verify the data, they can do random checks to see the uploads are done correctly i.e. the CCLA PDF is of that company & ICLA PDF is of that contributor.

**Comment by dealako** [comment]
We are closing this issue as we are receiving regular reports from the CNCF migration activity.
