### ISSUE TITLE
Contributor Troubleshooting

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#306]
**Impacted Docs**

- [/docs/contributors.md](https://github.com/communitybridge/easycla/blob/master/docs/contributors.md)
- [/docs/cla-troubleshooting.md](https://github.com/communitybridge/easycla/blob/master/docs/cla-troubleshooting.md)

**Tasks**
- [ ] Review help documents for impacts beyond what this issue explicitly calls out
- [ ] Update `contributor.md` file with provided verbiage
- [ ] Update `cla-troubleshooting.md` with provided verbiage
- [ ] Comment on any additional changes made relating to this issue, provide help doc link(s)

**Verbiage**

Starting on line 15 of `.../contributor.md`

----

### Having trouble contributing to EasyCLA-enforced repositories on GitHub?
1. Make sure your company email is verified in your [GitHub account settings](https://github.com/settings/emails).
1. Make sure your [commits are linked to the correct user](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user).
1. [Ask your CLA Manager](https://github.com/communitybridge/easycla/blob/master/docs/contribute-to-a-github-company-project.md#if-the-select-company-dialog-appears) to whitelist your GitHub Username, rather than your email.
1. If you believe you're a member of a whitelisted GitHub Organization, please <a href="https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership">make sure you've made that membership public</a>.
1. Try making your [GitHub email address](https://github.com/settings/emails) public.
1. Open a ticket in the [EasyCLA Support Queue](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

### Having trouble contributing to EasyCLA-enforced repositories on Gerrit?
1. Open a ticket in the [EasyCLA Support Queue](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

--------

Replace line 4 of [.../cla-troubleshooting.md](https://github.com/communitybridge/easycla/blob/master/docs/cla-troubleshooting.md)

--------

Contributors, please consult [/docs/contributors.md](https://github.com/communitybridge/easycla/blob/master/docs/contributors.md)
If you continue to have issues with EasyCLA, please [open a ticket in our queue](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

-------

**User Story**

As a contributor, I need more help in troubleshooting the issues I might encounter, so that I can resolve them myself if possible.

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved. Such as:

1. Doc update PR in review
2. Update Reviewed and Approved by Product Owner
