### ISSUE TITLE
Add GitLab Onboarding Documentation

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3124]
# Summary

Add GitLab Onboarding Documentation

# Background

The V2 EasyCLA documentation needs additional details on how to setup and configure GitLab via the PCC.

# Tasks

- [ ] Add instructions on how to add a GitLab Group/Organization to a project
- [ ] Add instructions on how to add repositories to a project
- [ ] Add instructions on how to remove/disable repositories from a project
- [ ] Add instructions on how to remove a GitLab Group/Organization from a project

# Acceptance Criteria

- [ ] Present documentation updates to the product owner

# References

- https://docs.linuxfoundation.org/lfx/v/v2/easycla/project-managers/add-and-manage-git-organizations-and-repositories

**Comment by dealako** [comment]
Closing issue due to inactivity.
