### ISSUE TITLE
Add/Update GitLab System Emails

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3126]
## Summary

Add/Update GitLab System Emails

## Background

This task is to add/update the system emails generated by the EasyCLA system. These emails should be reviewed and updated to support GitLab vocabulary.

## Tasks

- [ ] Review and update the system emails generated for the approval list updates. Ensure these updates include the GitLab username and GitLab Group approval list entries.
- [ ] REview and update the system emails generated/sent to Project Managers when GitLab Groups/Orgs and/or Repositories/Projects are added/updated/removed.

## Acceptance Criteria

- [ ] System emails are generated correctly and have the correct content.

## References

**Comment by dealako** [comment]
Closing issue due to inactivity.
