### ISSUE TITLE
Add OPNFV Project Setup and Templates 

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#325]
## Summary

Add OPNFV Project Setup and Templates to the EasyCLA system.

## Background

This is an onboarding activity.  The first steps are to create the project, set up the project manager and establish the templates.

## Tasks

- [x] Create the project in PROD
- [ ] Setup the initial project managers
- [x] Upload/customize the CCLA and ICLA templates

## Acceptance Criteria

Project is set up, managers configured and templates uploaded, reviewed and approved.

## References

OnBoarding Status Page: https://confluence.linuxfoundation.org/display/PROD/Project+Onboarding+Details+and+Status

**Comment by dealako** [comment]
Tasks completed:
- the foundation is set up already
- CLA group is set up and complete
- Uploaded PDFs to S3

**Comment by dealako** [comment]
Up next, @WillsonHG will add/update companies in PROD to ensure the CLA managers are on the company ACL.
