### ISSUE TITLE
EasyCLA v1 - Audit Report - Signatures

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#365]
## Summary

Build a tool that generates an audit report of the EasyCLA v1 signatures.

## Background

We need a tool that inspects the signature data stored in EasyCLA.  Since the database has undergone several data migrations, manual updates from admins, and numerous bug fixes, we want to identify any data integrity issue. This tool will evaluate each field in the database associated with the signature records.  The tool will highlight errors associated with any field for each record in the database.  Examples include `signature_reference_id` values that do not match a company or person or a `signature_company_id` that does not match a company record.  This report will generate an output file in the form of a CSV suitable for review in a spreadsheet.

## User Story

As a product owner and developer, I want to see a report of signature records that include invalid data.

## Tasks

- [x] Generate a command-line tool in python that evaluates signature records.
- [x] Allows the user to specify the AWS credentials profile name
- [x] Allows the user to specify output report filename
- [x] Report any issues outlined below in a format which allow an admin to verify/validate the issue:
      - include the signature id
      - include the type of error
      - include the invalidate field/column and invalid data
- [x] Identify signature records with invalid `signature_reference_id`.  All signature records must include this column and resolve it to a valid user record or company record.
- [x] Identify signature records with invalid `signature_company_id`, when set
- [x] Ensure that all records include a `signature_reference_type` field and have a value of either `user` or `company`.  No other values are allowed.
- [x] Ensure that all records include a `signature_type` field and have a value of either `cla` or `ccla`. No other values are allowed.
- [x] Ensure that Signature Employee records which are `signature_reference_type` that equal `user` and `signature_type` that equal `cla` include a `signature_user_ccla_company_id` which resolves to a valid company record.
- [x] Ensure that CCLA signature records which are `signature_reference_type` that equal `company` and `signature_type` that equal `ccla` do NOT include `signature_user_ccla_company_id` column
- [x] Ensure that ICLA signature records which are `signature_reference_type` that equal `user` and `signature_type` that equal `cla` do NOT include `signature_user_ccla_company_id` column.
- [x] Ensure that all signature records include a `signature_document_major_version` column
- [x] Ensure that all signature records include a `version ` column
- [x] Ensure that all signature records include a `signature_signed ` column
- [x] Ensure that all signature records include a `signature_approved ` column

## Acceptance Criteria

Run the audit report and share the results of the report with the EasyCLA administrators.

## References

```
Signature Record Truth Table:

| Type of Signature      | `signature_reference_type`| `signature_type` | `signature_reference_id` | `signature_user_ccla_company_id` |
|:-----------------------|:--------------------------|:-----------------|:-------------------------|:---------------------------------|
| ICLA (individual icon) | user                      | cla              | <user_id_value>          | null/empty                       |
| CCLA (employee icon)   | user                      | cla              | <user_id_value>          | <company_id_value>               |
| CCLA (company icon)    | company                   | ccla             | <company_id_value>       | null/empty                       |
```

**Comment by dealako** [comment]
@wanyaland I fixed write-up, changed `signature_company_id` to read `signature_user_ccla_company_id` in the Background section write-up.

**Comment by wanyaland** [comment]
> @wanyaland I fixed write-up, changed `signature_company_id` to read `signature_user_ccla_company_id` in the Background section write-up.

@dealako Noted. I shall add that field in the validation checks
