### ISSUE TITLE
Consolidate Linux Foundation Companies

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#370]
## Summary

We need to consolidate the two Linux Foundation companies in PROD.

## Background

Two Linux Foundation Companies exist is PROD. We need to consolidate these into one single entity "The Linux Foundation".

## Tasks

- [ ] Identify one of the two companies to keep. Identify one of the two companies to delete.
- [ ] Consolidate the Company Manager list - review/update as necessary - update the manager list for the company to keep.
- [ ] Identify references from other tables (signatures) that point to the company to be removed. Replace references with the company to keep.

## Acceptance Criteria

Only one Linux Foundation company in PROD.

**Comment by swinslow** [comment]
The correct legal name for the entity is "The Linux Foundation", so that would be my preference for the name of the final consolidated entry.

**Comment by WillsonHG** [comment]
I have completed the migration. I've moved all signature information from "Linux Foundation" to "The Linux Foundation" including signature_reference_id, signature_user_ccla_company_id, and user_company_id. The whitelists and acl's remained intact. I created mappings in s3 for each signature where needed.
