### ISSUE TITLE
Project Console - OPNFV Custom View

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#373]
## Summary

Project Console updates to include a custom view for the OPNFV project.

## Background

OPNFV leverages an "Agreement" instead of a CLA. They also include a document for LF Members, Non-LF members, and individual contributors.

## Tasks

- [x] Add a link to LF Member PDF
- [x] Update label to say LF Member Agreement, Non-LF Agreement, IC agreement
- [x] Maybe update other text to say "Agreement" instead of CLA??

## Acceptance Criteria

Demo OPNFV project console view to stakeholders.

**Comment by dealako** [comment]
Pushed PR #375 to address this. Merged and pushed to DEV.

**Comment by dealako** [comment]
![Screen Shot 2019-11-27 at 4 29 08 PM](https://user-images.githubusercontent.com/519609/69770391-bb396700-113d-11ea-960e-aa55ce31cdab.png)

**Comment by pranab-bajpai** [comment]
Verified changes during backlog grooming on 12/4
