### ISSUE TITLE
EasyCLA v1 - Audit Report - Project Template PDF Validation

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#379]
## Summary

Build a tool that generates an audit report of the EasyCLA project template PDF links.

## Background

We need a tool that inspects the Project template PDF links and determines if they are valid. This tool will report when the links are missing or invalid.

## Tasks

- [x] Generate a command-line tool in python that evaluates the project template PDF links. This tool will report the invalid project records including:
      - [ ] Missing `project_corporate_documents`
      - [ ] `project_corporate_documents` -> [0] -> `document_s3_url` is missing
      - [ ] `project_corporate_documents` -> [0] -> `document_s3_url` is invalid (link return a non-200 response and does not contain a valid PDF document.
      - [ ] Missing `project_individual_documents`
      - [ ] `project_individual_documents` -> [0] -> `document_s3_url` is missing
      - [ ] `project_individual_documents` -> [0] -> `document_s3_url` is invalid (link return a non-200 response and does not contain a valid PDF document.
- [x] Tool should allow the user to specify the AWS credentials profile name
- [x] Tool should allow the user to specify output report filename
- [x] Tool should report any issues outlined below in a format which allow an admin to verify/validate the issue:
      - include the project id
      - include the type of error
      - include the invalidate field/column and invalid data

## User Story

As an LF Admin, I want to know if project template documents are not set or invalid.

## Acceptance Criteria

Run the audit report on DEV and STAGING and share the results of the report with the EasyCLA administrators.

## References

```
Signature Record Truth Table:

| Type of Signature      | `signature_reference_type`| `signature_type` | `signature_reference_id` | `signature_user_ccla_company_id` |
|:-----------------------|:--------------------------|:-----------------|:-------------------------|:---------------------------------|
| ICLA (individual icon) | user                      | cla              | <user_id_value>          | null/empty                       |
| CCLA (employee icon)   | user                      | cla              | <user_id_value>          | <company_id_value>               |
| CCLA (company icon)    | company                   | ccla             | <company_id_value>       | null/empty                       |
```

**Comment by pranab-bajpai** [comment]
@wanyaland demo'ed this during scrum on 12/4
