### ISSUE TITLE
EasyCLA v1 - Audit Report - Companies

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#380]
## Summary

Build a tool that generates an audit report of the EasyCLA v1 companies.

## Background

We need a tool that inspects the companies data stored in EasyCLA.  Since the database has undergone several data migrations, manual updates from admins, and numerous bug fixes, we want to identify any data integrity issue. This tool will evaluate each field in the database associated with the companies records.  The tool will highlight errors associated with any field for each record in the database.  This report will generate an output file in the form of a CSV suitable for review in a spreadsheet.

## User Story

As a product owner and developer, I want to see a report of company records that include invalid data.

## Tasks

- [x] Generate a command-line tool in python that evaluates company records.
- [x] Allows the user to specify the AWS credentials profile name
- [x] Allows the user to specify output report filename
- [x] Report any issues outlined below in a format which allow an admin to verify/validate the issue:
      - [ ] missing `company_manager_id` column
      - [ ] `company_manager_id` does not resolve to a valid user in the users table
      - [ ] `company_name` is missing or blank
      - [ ] missing `date_created` column
      - [ ] missing `date_modified` column

## Acceptance Criteria

Run the audit report and share the results of the report with the EasyCLA administrators.

## References

```
Signature Record Truth Table:

| Type of Signature      | `signature_reference_type`| `signature_type` | `signature_reference_id` | `signature_user_ccla_company_id` |
|:-----------------------|:--------------------------|:-----------------|:-------------------------|:---------------------------------|
| ICLA (individual icon) | user                      | cla              | <user_id_value>          | null/empty                       |
| CCLA (employee icon)   | user                      | cla              | <user_id_value>          | <company_id_value>               |
| CCLA (company icon)    | company                   | ccla             | <company_id_value>       | null/empty                       |
```

**Comment by pranab-bajpai** [comment]
@dealako verified this is working
