### ISSUE TITLE
EasyCLA Event Log API

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#393]
## Summary

The EasyCLA system requires an event log to store key events that occur within the system. This log will be used for auditing and system validation.

## Background

During a recent review, the stakeholders requested that we add a way to store events from the EasyCLA system. These events will be written once and not updated or deleted.  This capability is now in the v2 system.  This task is to retrofit the existing v1 system with the event log.
 
## User Story

- As an LF Admin, I want to see the events from the EasyCLA system.

## Tasks

- The EasyCLA system has an event table for the EasyCLA system, see:
https://github.com/LF-Engineering/easycla-private/blob/master/deploy/cla-backend/serverless.yml#L645-L680, https://github.com/LF-Engineering/easycla-private/blob/master/deploy/cla-backend/serverless.yml#L75, https://github.com/LF-Engineering/easycla-private/blob/master/deploy/cla-backend/serverless.yml#L165-L178
- [x] The next step is to add dynamodb data models in this file:  https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py. This should be similar to the other classes, such as the CompanyModel: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py#L2046 and the Company Class: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py#L2065
- [x] this table will be called events, and follow a similar schema/structure to: https://github.com/communitybridge/easycla-api/blob/master/.build/db/schema.sql#L80
- [x] the database model will allow CREATE/GET/SEARCH, but not UPDATE or DELETE (for legal reasons).

## Acceptance Criteria

Demonstrate that the system can create, search/get events.

## References

See above
