### ISSUE TITLE
Python DynamoDB API Update

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#460]
## Summary

Update the Python DynamoDB API

## Background

Additional columns were added to the DynamoDB database schema.  This ticket is to retrofit the Python API with additional columns and indices that were added.

## Tasks

- [x] Users Table - add support for the `user_external_id` column 
- [x] Users Table - add support for the `github-user-external-id-index` index
- [ ] Company Table - add support for the `company_external_id` column (may already be there) 
- [ ] Company Table - add support for the `external-company-index` index (may already be there)
- [x] Signature Table - add support for the `signature_project_external_id` column 
- [x] Signature Table - add support for the `project-signature-external-id-index` index
- [x] Signature Table - add support for the `signature_company_signatory_id` column 
- [x] Signature Table - add support for the `signature_company_signatory_name` column 
- [x] Signature Table - add support for the `signature_company_signatory_email` column
- [x] Signature Table - add support for the `signature-company-signatory-index` index
- [x] Signature Table - add support for the `signature_company_initial_manager_id` column 
- [x] Signature Table - add support for the `signature_company_initial_manager_name` column 
- [x] Signature Table - add support for the `signature_company_initial_manager_email` column
- [x] Signature Table - add support for the `signature-company-initial-manager-index` index
- [x] Signature Table - add support for the `signature_company_secondary_manager_list` column (JSON BLOB)

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [DynamoDB Database Schema](https://confluence.linuxfoundation.org/display/PROD/EasyCLA+Version+1+Database+Schema+Walkthrough)
