### ISSUE TITLE
Domain Regex Not Working

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#484]
## Summary

When testing email patterns, it was reported that a valid email which should have passed the domain whitelist failed.

## Background

Email domains can be added to the Corporate console whitelist. When an email is tested against the domain values, it should pass or fail accordingly.  A use-case was reported that a user's email was not passing the domain whitelist. Upon investigation, it appears that the Python code conducts some pre-processing of the domain regex prior to testing the email aginst the domain pattern.  This preprocessing appears to be faulty.

## Expected behavior

Domain whitelist entries should pass/fail email addresses as expected.

## Screenshots

N/A - backend logic

## Environment

The discovery of this issue occurred in PROD.

## Tasks

- [ ] Understand regex pattern provided from the UX whitelist. In this case, it was (identified from the logs) two domain values: ['*.att.com', '*att.com'].
- [ ] Review the input email address abc@att.com. Email address should pass, but according to the log the regex was changed to `^.*@.*\.att.com$`, see:
```
Did not match email: abc@att.com with domain: ^.*@.*\.att.com$ for user: id: f3d92587-e15c-4918-a41e-9459da4cc56d, username: None, gh id: None, gh username: None, lf email: abc@att.com, emails: {'abc@att.com'}, ldap id: None, lf username: kk4281, user company id: None, note: None
```
- [ ] Review the regex preprocessing logic in the code: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py#L1530-L1535. Update the logic to pass the checks when appropriate.
- [ ] Write unit tests with numerous good/bad example for this bit of code (recommend creating a separate function so that can properly test and reuse this old logic).
- [ ] Ensure unit tests are run as part of the CI/CD process.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

CloudWatch Logs: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-apiv2;stream=2020/01/09/[$LATEST]6514fcd6ab1a42f38be01c31a54bddc8;start=2020-01-08T14:52:25Z

Relevant pieces from the log (email address below replaced with 'abc' to protect privacy):
```
2020-01-09T14:52:25 DEBUG cla: Did not match email: abc@att.com with domain: ^.*@.*\.att.com$ for user: id: f3d92587-e15c-4918-a41e-9459da4cc56d, username: None, gh id: None, gh username: None, lf email: abc@att.com, emails: {'abc@att.com'}, ldap id: None, lf username: abc, user company id: None, note: None
2020-01-09T14:52:25 DEBUG cla: Did not match email: abc@att.com with domain: ^.*@.*\.att.com$ for user: id: f3d92587-e15c-4918-a41e-9459da4cc56d, username: None, gh id: None, gh username: None, lf email: abc@att.com, emails: {'abc@att.com'}, ldap id: None, lf username: abc, user company id: None, note: None
```

Relevant code in the Python Backend: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py#L1517-L1550
