### ISSUE TITLE
EasyCLA Audit Service - Golang

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#490]
**Summary**

Create an Audit Service for recording events in the EasyCLA system on the Golang backend.

**Background**

Since the EasyCLA system processes permissions relating to legal CLA documents, a comprehensive audit log needs to record all access and permission events.  Examples include add permission, delete permission, create a signature, delete a signature, add/update/delete whitelist entry.

**Task**

Suggested columns - match python side and infra table definition:
- id: pk GUID type v4 or something similar
- event: string (we will have a set of enum values)
- user: string (id of the user/person who created the event - e.g. logged in user)
- project id: string (id of the SFID project)
- company id: string (id of the organization/company)
- event date time (date-time of the event)
- event_data: blob, contain event details, such as: `{"github_whitelist": ["prasannamahajan", "ddeal"]}`

Also:

- [x] create a Swagger specification for `SearchEvent `, should include search by event type, by the user, project id, company/org, and by a time window. Support any combination of these parameters.  Also, include pagination params as well: page_size/limit, offset, order_by as the list of events may/will be large.
- [x] create a repo implementation for `SearchEvent`
- [x] create a service layer for `SearchEvent`
- [x] add the handler/service/repo to the setup/glue it together for `SearchEvent`.
- [x] create a repo implementation for `CreateEvent`
- [x] create a service layer for `CreateEvent` - note: this service will NOT have a public endpoint or definition in swagger.
- [x] test/validate creating and retrieving audit values

We’ll use this for auditing everything in the backend/events, etc.

**Use Cases**

As a project manager, I want to see events related to my project.
As a CLA Manager, I want to see events related to my company for a given project
As an LF Admin, I want to see all events of a specific type

**Search criteria**

- search by project_id - Project Managers might want to see all events related to their project
- search by project_id + company_id - Classic example of event from the Corporate Console
- search by company_id - Company Admins might want to see all their events (maybe less useful as most of the time CLA Managers will search Project id + company id)
- search by event_type - Find all events of a specific type (e.g. failed CLA checks, - added user to whitelist)

**Acceptance Criteria**

- [ ] Unit tests for create/delete audit events
- [ ] Create function tests for audit events (see @dealako for CI/CD automation)
- [ ] Demonstration of audit service to product owners

**References**

We have similar examples of a Search Endpoint used in the Platform Core Services, such as the Organization Service: https://github.com/LF-Engineering/organization-service/blob/master/swagger/organization-service.yaml#L61 (private repo).

**Comment by dealako** [comment]
Changes pushed to DEV.
