### ISSUE TITLE
EasyCLA Audit Service - Python Backend

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#538]
## Summary

Python backend needs to record auditable events.

## Background

We need to add hooks for the Python backend to record key events.

## Tasks

- [ ] Projects - all operations except for get/search/query
- [ ] Companies - all operations except for get/search/query
- [ ] Uses - all operations except for get/search/query
- [ ] Signatures - all operations except for get/search/query
- [ ] WhiteLists - all operations, including add/update/delete whitelist entries to the signature record
- [ ] When we send an email to the CLA Manager or Contributors

Later, we can consider if we should log all the pass/fail events from Gerrit and GitHub - this list could grow very very large over time. We would need a strategy to determine how to manage this volume of information over time - perhaps a separate table with a TTL.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Events are generated at the above key areas in the code - can view the events in DynamoDB directly or through the UI (if the feature is complete)
1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Work completed.
