### ISSUE TITLE
Confirm Signature Version

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#539]
## Summary

When performing queries for signatures, we should always check that we are using the correct version.

## Background

Review the backend Go and Python API logic. Review where we query for CCLA, Employee Signature, and ICLA signatures. Ensure that the logic is reviewing the version identifiers to ensure we are fetching the correct version when applicable.

## Tasks

- [x] Queries for signatures should review and use the lastest signature version (major and minor) - Python side, I think, does this correct. Ensure this is indeed correct and also accomplished on the golang side.
- [x] Queries should also review the approved flag - most use-cases should return signatures where approved = true
- [x] Queries should also review the signed flag - most use-cases should return signatures where signed = true
 
## User Story

As a user of the CLA system, queries should return the most recent signature that I have created/signed.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by prasannamahajan** [comment]
We don't check major version of the signature.

**Comment by prasannamahajan** [comment]
![UserSignedProjectSignature](https://user-images.githubusercontent.com/1476068/74238301-85972980-4cfb-11ea-8fd6-8b84616abf50.jpeg)
