### ISSUE TITLE
Add audit event for employee signature

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#571]
## Summary
Add Audit events when 
1) user is associated with company
2) employee signature is created.
3) employee signature is updated (when existing contributor is removed from whitelist we set approved flag as false)

## Background

We want to record audit events related to employee signature. 

## Task
- [x] Add event when user is associated with company
- [x] Add event when employee signature is created
- [x] Add event when employee signature is updated
 
## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Above events are generated
1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.
