### ISSUE TITLE
Project Console - v1 - Update CLA Group API Calls

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#677]
## Summary

Project Console - v1 - Update CLA Group API Calls

## Background

The Project Management Console currently uses a combination of golang and python backend API calls for the CLA Group creation, search, read, update, delete.

This task is to migrate the existing Python API calls to use the newer Golang API calls. The reason for this includes:
- Golang API calls will be used directly in the V2 LFX
- Golang API calls have been updated with the proper permissions
- Golang API calls include a number of bug fixes (e.g. prevent duplicate CLA Group Names)

## Tasks

- Navigate to the Project Management Console
- Select a Foundation/Project
- From the CLA Group Page:
  - [x] Review the API calls used in this page.
  - [x] Create New CLA Group should use the v3 Golang API (update UI TS code) - *note* payload/body and response models match but need migration from snake_case to camelCase
  - [x] Update CLA Group Name should use the v3 Golang API
  - [x] Read/Search/List CLA Groups should use the v3 Golang API
- [x] Identify remaining API calls that leverage Python that are not in the Golang backend.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- EasyCLA API - [CLA Group/Project API](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L717-L917)
- [EasyCLA API Functional Tests](https://github.com/communitybridge/easycla/blob/master/tests/rest/test_v3_project_api.tavern.yaml) - Shows CRUD operations
- See @dealako for PostMan setup help

**Comment by hnexokonkwo** [comment]
@nirupamav pushed to DEV, ready for review/QA.

**Comment by dealako** [comment]
PMC should work as before without any regressions.

**Comment by nirupamav** [comment]
Verified below scenarios and logged bug #739, #719 
1. Configure/Add Github Organization
2. Add/Update CLA Group
3. Select and generate Templates
4. Add/Update Github Repositories
5. Download generated templates
6. View Signatures
7. View Companies
