### ISSUE TITLE
Project Console - Add GitHub Org - Page Refresh

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#703]
## Summary

Observed: Component/Card refresh stalls after adding/canceling the GitHub org add spins.

## Background

While testing the Add/Remove GitHub Organization in the Project Management console, it was observed that after the modal close the GitHub Organization Card shows the spinning icon/control.  This spinning/busy control never completes and the card never completes rendering of the GH Organizations.

## Expected behavior

The GH Organization list should complete and show the updated GH Orgs.

## Screenshots

![Screen Shot 2020-03-17 at 10 21 22 AM](https://user-images.githubusercontent.com/519609/76883573-9f1b1c00-6839-11ea-9155-53aedfc579ae.png)

## Environment

Please complete the following information:

* Environment: DEV 

To reproduce:
- Navigate to the dev project management console
- Select the ASF Foundation
- Select Connect GitHub Organization
- Cancel the Dialog (don't add)
- Observe the modal is dismissed
- Observe the GitHub Organization list attempts to refresh
- Observe the GitHub Organization list never refreshes (spinning icon)

## Task

- [x] Identify the API call that is stalling
- [x] Trap any API errors/error responses - show users any relevant error messages
- [x] Dismiss the spinning icon
- [x] Recommend possible solutions
- [x] Updated the refresh logic so that only the minimal set of API calls/refresh is done. E.g. can we only refresh the top GH Organizations card?

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by hnexokonkwo** [comment]
@dealako the GitHub organization refreshes but it takes quite a while to complete the refresh process because it runs a loop to get all the repository groups by organisation and gerrit

**Comment by dealako** [comment]
I have added another task item to this ticket:

- Updated the refresh logic so that only the minimal set of API calls/refresh is done. E.g. can we only refresh the top GH Organizations card?

Are we trapping the errors properly and showing an error message on error?  I don't think so.

**Comment by hnexokonkwo** [comment]
@nirupamav pushed to DEV, ready for review/QA.

**Comment by nirupamav** [comment]
**_Verified below scenarios and observed auto refresh works as expected without any issues_**
1. Delete an already configured GitHub organization (Organization configured without any errors and Organization not configured properly and has error)
2. Click on CONNECT GITHUB ORGANIZATION and click CLOSE in the "Add GitHub Organization" popup
3. Click on CONNECT GITHUB ORGANIZATION -> Enter valid org name -> click CONNECT in the "Add GitHub Organization" popup -> Click CLOSE
4. Click on CONNECT GITHUB ORGANIZATION -> Enter valid org name -> click CONNECT in the "Add GitHub Organization" popup -> Click DONE
5. Click on CONNECT GITHUB ORGANIZATION -> Enter valid org name -> click CONNECT in the "Add GitHub Organization" popup -> Click INSTALL -> Install or configure the app -> After installation click on the tab where Project Console is opened -> Page is not auto refreshed (bug #754 logged for this issue) -> refresh the page
