### ISSUE TITLE
V2 Integration - CLA Group + Repository Query

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#705]
## Summary

In order to support the V2 Integration and v1 UI Optimizations, we need to provide a consolidated API for the CLA Group and Repository Query.

## Background

This API update will support both the v1 legacy UI and the new V2 API.

## Tasks

- [x] Review the v3/project/external/{sfid} (e.g. a09410000182dD2AAI) API response, note that it returns a list of CLA Groups with associated details.
- [x] Review the v1/project/{interal_project_id}/gerrits API call which retrieves Gerrit repositories for the given CLA group
- [x] Review the v1/project/{internal_project_id}/repositories_group_by_organization API call which retrieves the GitHub repos for a given CLA group
- [x] Consolidate the old python Gerrits and GitHub API calls to include the repositories under the CLA Group response model.  When possible, use Go routines to parallelize the queries to the Gerrit and GitHub tables
- [x] Test and verify
- [x] Add a new (LFX) V2 API endpoint for the v3/project/external/{sfid} which calls the legacy (v3) implementation
- [x] Add the new endpoint to the ACS CLI configuration/repo
- [x] Send a note to @hnexokonkwo so that he can replace the client-side API calls with the new optimized/consolidated calls.
- [ ] Once UI is updated, remove the old v1 Python API calls (quickly scan the UI) - should only be used in the project console UI

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Task implemented - will remove Python code later.
