### ISSUE TITLE
API - LFX v2 Templates

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#749]
## Summary

Add LFX v2 Templates

## Background

Add the following API endpoints to the /v4 LFX v2 API:

- [/template](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L1403)
- [/clagroup/{claGroupId}/template](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L1425)

## Tasks

- [x] Review the GET templates API
- [x] Create corresponding [cla.v2.yaml](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.v2.yaml) endpoints - leverage existing data models
- [x] Add acs-cli configuration (view_all)
- [x] Write function tests
- [x] Test/validate
- [x] Demonstrate to product owners

## User Story

As an LFX user, I want to load the CLA templates.
As an LFX user, I want to save a CLA template

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

See embedded links above

**Comment by prasannamahajan** [comment]
Pull Request: https://github.com/communitybridge/easycla/pull/756

**Comment by dealako** [comment]
Reviewed - closing.
