### ISSUE TITLE
migrate github organization api to golang

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#781]
## Summary

Several of the APIs used by the Project management console need migration to golang to support 1) consolidated queries and 2) LFX V2 API integration.

## Background

Migrate the following Python APIs to Golang (v3):

delete /v1/github/organizations/{orgName}
post /v1/github/organizations

Provide Golang implementation for two endpoints:
- [x] Include these endpoints into the v3 swagger specification, review, and cleanup API endpoint/path as necessary
- [x] Define the request, response, and error models in the swagger specification. Ensure documentation/examples are added to support api-docs readability.
- [x] If possible, when possible, consolidate the API quests into one endpoint (e.g. avoid duplicate/similar endpoints and data models)
- [x] Develop the golang handler to support the new v3 endpoints
- [x] Develop the service handler
- [x] Develop the repository/database handler
- [x] Write functional tests to query known data in DEV
- [x] Write v4 swagger specification - provide pass-through to v3 data models
- [x] Update acs-cli specification to allow queries of GH/Gerrit data for authenticated users (view_all for now).
 
## User Story

As a developer, I want to optimize the PMC queries.
As a developer, I want to consolidate API requests to the golang backend API.
As a developer, I want to support LFX v2 integration by using golang to invoke the legacy v3 API

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by prasannamahajan** [comment]
Pull request : https://github.com/communitybridge/easycla/pull/797

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**_POST ACTION_**
1. **500 is returned instead of 401 when expired authorization token is provided**
![image](https://user-images.githubusercontent.com/60865903/80945944-917e1d80-8e0a-11ea-8ec8-503912ebd233.png)
2. **There is no validation on OrganizationName. Post is successful even if invalid org is added**
![image](https://user-images.githubusercontent.com/60865903/80946013-bf636200-8e0a-11ea-8602-9506ce2eb76e.png)
![image](https://user-images.githubusercontent.com/60865903/80946064-ddc95d80-8e0a-11ea-8b2f-27fa3e964aaa.png)
3. **Able to add github org even if invalid external projectId is provided**
![image](https://user-images.githubusercontent.com/60865903/80946176-149f7380-8e0b-11ea-859b-5a5c4974d4a6.png)



**_GET ACTION_**
1. **200 is returned when invalid external project ID is provided. 404/400 should be returned to be consistent with other api's**
![image](https://user-images.githubusercontent.com/60865903/80945530-9f7f6e80-8e09-11ea-9376-b6334be1e5bf.png)
2. **500 is returned instead of 401 when expired authorization token is provided**
![image](https://user-images.githubusercontent.com/60865903/80945603-c63da500-8e09-11ea-9cc1-ed2cc96f5f61.png)

**_DELETE ACTION_**
1. **200 is returned instead of 204**
![image](https://user-images.githubusercontent.com/60865903/80945744-1ddc1080-8e0a-11ea-8fc6-f03e9dd1a4cc.png)
2. **Appropriate response message is not displayed when invalid github organization is provided**
![image](https://user-images.githubusercontent.com/60865903/80945808-48c66480-8e0a-11ea-8dcb-46721fc58601.png)
3. **500 is returned instead of 401 when expired authorization token is provided**
![image](https://user-images.githubusercontent.com/60865903/80945853-6dbad780-8e0a-11ea-991c-4f2b1dee40e4.png)

**Comment by dealako** [comment]
@makkalot can you review the 500 token expired error?  Is this related to the GH session token? Can we determine if the token is expired and possibly refresh?

**Comment by makkalot** [comment]
seems the issue is happening in Authorizer when the jwt token is expired, not related to github in this case

![Screenshot 2020-10-02 at 13.52.35.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/80933426-6b03-4837-a2ba-4c3173ffb6b2)

**Comment by nirupamav** [comment]
@rinkeshbhutwala @dealako 
As per description in ticket V1 endpoints were to be migrated to V3. However I see that still V1 endpoints are used. I have been reopening this ticket many times but still I see same issue. Also observed that now even for delete and get V1 endpoints are used. Is so where are we using V3 endpoints? and if they are not used are we supposed to test this tciket?

Since this ticket was closed wanted to know if all the issues that I mentioned above are fixed for V3 endpoint?

**Comment by dealako** [comment]
## Summary

@amolsontakke3576 re-assigning this task to you. I did a quick search in the v1 project console UI. If you review the [cla.service.ts /v1 API calls](https://github.com/communitybridge/easycla/blob/master/cla-frontend-project-console/src/ionic/services/cla.service.ts#L38) and perform a "find usages" search, you will notice that we still have a number of functions that call the v1 backend API.  We need to replace these endpoint API calls with /v3 endpoint API calls.

![Screen Shot 2020-10-05 at 1.50.50 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/82bc6be3-a23a-4d0f-b161-7ed516a2710c)

## Tasks

- [ ] Identify the components that call and rely upon the `/v1/github/organizations` API call. Replace with /v3 endpoints. Identify any API gaps that we have, if any.  Remove the v1 function definition from the cla.services.ts file.
- [ ] Identify the components that call and rely upon the `/v1/repository` and `/v1/repository/' + repositoryId` repository endpoints. Replace with the /v3 endpoints. Identify any API gaps that we may have, if any.  Remove the v1 function definitions from the cla.services.ts file.
- [ ] Test and validate
- [ ] Demonstrate to the stakeholders (Pranab and David) in standup

**Comment by dealako** [comment]
Closing issue. Will re-evaluate at a later date.
