### ISSUE TITLE
migrate repositories api to golang

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#798]
## Summary

Several of the APIs used by the Project management console need migration to golang to support 1) consolidated queries and 2) LFX V2 API integration.

## Background

Migrate the following Python APIs to Golang (v3):
POST  /v1/repository
DELETE  /v1/repository/<repositoryId>
GET  /v1/project/<projectId>/configuration_orgs_and_repos

Provide Golang implementation for two endpoints:
- [ ] Include these endpoints into the v3 swagger specification, review, and cleanup API endpoint/path as necessary
- [ ] Define the request, response, and error models in the swagger specification. Ensure documentation/examples are added to support api-docs readability.
- [ ] If possible, when possible, consolidate the API quests into one endpoint (e.g. avoid duplicate/similar endpoints and data models)
- [ ] Develop the golang handler to support the new v3 endpoints
- [ ] Develop the service handler
- [ ] Develop the repository/database handler
- [ ] Write functional tests to query known data in DEV
- [ ] Write v4 swagger specification - provide pass-through to v3 data models
- [ ] Update acs-cli specification to allow queries of data for authenticated users 
 
## User Story

As a developer, I want to optimize the PMC queries.
As a developer, I want to consolidate API requests to the golang backend API.
As a developer, I want to support LFX v2 integration by using golang to invoke the legacy v3 API

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by prasannamahajan** [comment]
Pull request: https://github.com/communitybridge/easycla/pull/815

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**_POST ACTION_**
1. **Observed 401 is returned when invalid external projectid is provided. 404/400 should be returned to be consistent with other V3 api's** 
![image](https://user-images.githubusercontent.com/60865903/80943560-1a925600-8e05-11ea-878e-a80cd7646402.png)
2. **Able to add invalid github details**
![image](https://user-images.githubusercontent.com/60865903/80944504-5dedc400-8e07-11ea-97aa-49e73b35531d.png)
3. **Able to add when invalid projectId(CLA Group Id) is provided**
![image](https://user-images.githubusercontent.com/60865903/80944799-f7b57100-8e07-11ea-92d7-11464768cc9c.png)
4. **Able to add without repository name**
![image](https://user-images.githubusercontent.com/60865903/80945052-9215b480-8e08-11ea-9bc3-3bbe53f2ff32.png)

![image](https://user-images.githubusercontent.com/60865903/80945067-9b9f1c80-8e08-11ea-8de1-d051495fb899.png)
5. **500 is returned instead of 401 when authorization token is expired**
![image](https://user-images.githubusercontent.com/60865903/80945142-c5584380-8e08-11ea-95d4-5ebdc8730022.png)

**_GET ACTION_**
1. **500 is returned instead of 401 when authorization token is expired**
![image](https://user-images.githubusercontent.com/60865903/80945242-02243a80-8e09-11ea-8aca-edf85189869d.png)
2. **Observed 401 is returned when invalid external projectid is provided. 404/400 should be returned to be consistent with other V3 api's** 
![image](https://user-images.githubusercontent.com/60865903/80945315-2d0e8e80-8e09-11ea-8629-549ba548dc29.png)


**_DELETE ACTION_**
1. **200 is returned instead of 204**
![image](https://user-images.githubusercontent.com/60865903/80943819-b3c16c80-8e05-11ea-83b1-1f2b7fa8315d.png)
2. **Observed 401 is returned when invalid external projectid is provided. 404/400 should be returned to be consistent with other V3 api's** 
![image](https://user-images.githubusercontent.com/60865903/80943880-db183980-8e05-11ea-978d-20c149856d04.png)
3. **500 is returned instead of 401 when authorization token is expired**
![image](https://user-images.githubusercontent.com/60865903/80943945-0a2eab00-8e06-11ea-9ced-3e7d14e4ffa9.png)


**_IN UI still V1 api's are used for GET, POST and DELETE_**
![image](https://user-images.githubusercontent.com/60865903/80943244-61338080-8e04-11ea-9e78-7b8735d18468.png)

**Comment by nirupamav** [comment]
**_Tested and observed that below issues are still reproducible._**

**_POST ACTION_**
**5. 500 is returned instead of 401 when authorization token is expired**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e74a9847-6055-4a03-b450-ded806aae965)

**6. Not able to add Repositories even when valid details are provided. Due to this issue testing of issues 2,3,4 are blocked**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8be2dd63-35db-4cd6-bea1-1c311379984a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4c51d346-1ca2-4ff4-9129-4fdd11102198)

**_GET ACTION_**
**1. 500 is returned instead of 401 when authorization token is expired**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7e319c9b-c6b9-4510-a802-0a93bcc17700)

**_DELETE ACTION_**
**3. 500 is returned instead of 401 when authorization token is expired**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/45c81bd8-cf9f-454e-8d4f-7409715f4f1b)


**IN UI still V1 api's are used for GET, POST and DELETE**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/24f967df-1226-4a47-b2bf-b4f0571b989d)

**Comment by rinkeshbhutwala** [comment]
@nirupamav For Issue no. 6 I have verified that Data is not stored properly in cla tables or it might be wrong data in tables that's why error is coming **cla-group is not linked with given project SFID** 
Can you please check with fresh data i.e. create a new cla-group and try the whole workflow?

**Comment by nirupamav** [comment]
@rinkeshbhutwala 
It is the correct data. I am using it in V1 for testing

**Comment by dealako** [comment]
@makkalot can you review the 500 token expired error? Is this related to the GH session token? Can we determine if the token is expired and possibly refresh?

Relates to #781

**Comment by dealako** [comment]
## Summary

@amolsontakke3576 re-assigning this task to you. I did a quick search in the v1 project console UI. If you review the cla.service.ts /v1 API calls and perform a "find usages" search, you will notice that we still have a number of functions that call the v1 backend API. We need to replace these endpoint API calls with /v3 endpoint API calls.

![Screen Shot 2020-10-05 at 1.50.50 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/6937f6ac-1a3c-4fee-8221-aa5b34a47db5)

## Tasks
- [ ] Identify the components that call and rely upon the /v1/github/organizations API call. Replace with /v3 endpoints. Identify any API gaps that we have, if any. Remove the v1 function definition from the cla.services.ts file.
- [ ] Identify the components that call and rely upon the /v1/repository and /v1/repository/' + repositoryId repository endpoints. Replace with the /v3 endpoints. Identify any API gaps that we may have, if any. Remove the v1 function definitions from the cla.services.ts file.
- [ ] Test and validate
- [ ] Demonstrate to the stakeholders (Pranab and David) in standup

Related to #781

**Comment by amolsontakke3576** [comment]
@David @rinkeshbhutwala 
I have verified Project consoles endpoints and below are a few that still use V1.
1. getAllProjectsFromSFDC :  `/v1/salesforce/projects`
2. getProjectFromSFDC : ` /v1/salesforce/project?id=`
3. getProjectConfigurationAndRepos : `/v1/project/' + projectId + '/configuration_orgs_and_repos`

Below are few endpoints in the Corporate console still uses V1 
1. putSignature : `/v1/signature`
2. postCompany : `/v1/company`
3. getCLAManagers : `/v1/signature/' + signatureId + '/manager`
4. getCompanyUnsignedProjects : `/v1/company/' + companyId + '/project/unsigned`
5. postCorporateSignatureRequest : `/v1/request-corporate-signature`

1. postOrGetUserForGerrit : `/v1/user/gerrit`
2. gettGerritProjects : `/v1/project/' + projectId + '/gerrits`

Can you please suggest equivalent endpoints in Go lang?

**Comment by rinkeshbhutwala** [comment]
@amolsontakke3576 Can you please share more details regarding the above endpoints so I can find the equivalent v3 and v4 endpoint and provide you as soon as possible earlier.

**Comment by amolsontakke3576** [comment]
**For Project Console**

Request URL: https://api.lfcla.dev.platform.linuxfoundation.org/v1/salesforce/projects
Request Method: GET
Response : 
```
[
  {
    "name": "The Linux Foundation",
    "id": "a0941000002wBz9AAE",
    "description": "The Linux Foundation is dedicated to building sustainable ecosystems around open source projects to accelerate technology development and industry adoption.\nFounded in 2000, the Linux Foundation provides unparalleled support for open source communities through financial and intellectual resources, infrastructure, services, events, and training. Working together, the Linux Foundation and its projects form the most ambitious and successful investment in the creation of shared technology.",
    "logoUrl": "https://s3.amazonaws.com/cla-project-logo-dev/a0941000002wBz9AAE.png"
  },
  {
    "name": "Janusgraph",
    "id": "a0941000002wBybAAE",
    "description": "JanusGraph is a scalable graph database optimized for storing and querying graphs containing hundreds of billions of vertices and edges distributed across a multi-machine cluster.",
    "logoUrl": "https://s3.amazonaws.com/cla-project-logo-dev/a0941000002wBybAAE.png"
  }
]
```
Request URL: https://api.lfcla.dev.platform.linuxfoundation.org/v1/salesforce/project?id=a09410000182dD2AAI
Request Method: GET
Response : 
```
{
  "name": "Academy Software Foundation",
  "id": "a09410000182dD2AAI",
  "description": "The mission of the Academy Software Foundation (ASWF) is to increase the quality and quantity of contributions to the content creation industry\u2019s open source software base; to provide a neutral forum to coordinate cross-project efforts; to provide a common build and test infrastructure; and to provide individuals and organizations a clear path to participation in advancing our open source ecosystem.",
  "logoUrl": "https://s3.amazonaws.com/cla-project-logo-dev/a09410000182dD2AAI.png"
}
```
Request URL: https://api.lfcla.dev.platform.linuxfoundation.org/v1/project/486a553d-a1bd-4d78-b28f-914606c5f08f/configuration_orgs_and_repos
Request Method: GET
Response: 
```
{
  "orgs_and_repos": [
    {
      "auto_enabled": false,
      "branch_protection_enabled": false,
      "date_created": "2020-11-24T08:13:16.000000+0000",
      "date_modified": "2020-11-24T08:14:11.822523+0000",
      "organization_company_id": null,
      "organization_installation_id": "13150379",
      "organization_name": "TestBugsEasyCLAV2",
      "organization_name_lower": "testbugseasyclav2",
      "organization_project_id": null,
      "organization_sfid": "a0941000002wBz4AAE",
      "project_sfid": "a0941000002wBz4AAE",
      "version": "v1",
      "repositories": [
        {
          "repository_github_id": 315303902,
          "repository_name": "TestBugsEasyCLAV2/TestBugsEasyCLAV2-001",
          "repository_type": "github",
          "repository_url": "https://github.com/TestBugsEasyCLAV2/TestBugsEasyCLAV2-001",
          "enabled": true
        }
      ]
    }
],
"repositories": [
    {
      "date_created": "2020-09-03T11:02:17.000000+0000",
      "date_modified": "2020-10-22T11:53:18.000000+0000",
      "enabled": false,
      "note": "created on 2020-09-03T11:02:17Z. disabled on 2020-10-22T11:53:18Z",
      "project_sfid": "a092M00001IfVmKQAV",
      "repository_external_id": "276077439",
      "repository_id": "f2493e5b-b4d0-4e1a-a343-6553d6b22393",
      "repository_name": "lkkondepudi/repo1",
      "repository_organization_name": "lkkondepudi",
      "repository_project_id": "cd9548ee-0137-4641-a817-d6ae842e95b4",
      "repository_sfdc_id": "a0941000002wBz4AAE",
      "repository_type": "github",
      "repository_url": "https://github.com/lkkondepudi/repo1",
      "version": "v1"
    }
]
}
```

**Comment by amolsontakke3576** [comment]
@rinkeshbhutwala Please check corporate console V1 API details in the below attachment
[https://app.zenhub.com/files/194341141/5d2a536d-c7c9-42bf-8174-67c893980e0b/download](https://app.zenhub.com/files/194341141/5d2a536d-c7c9-42bf-8174-67c893980e0b/download)

**Comment by amolsontakke3576** [comment]
@rinkeshbhutwala Please check contributor console V1 API details in the below attachment
[https://app.zenhub.com/files/194341141/7eeacdc9-d5f4-446b-a4c8-a63fdd4dc03d/download](https://app.zenhub.com/files/194341141/7eeacdc9-d5f4-446b-a4c8-a63fdd4dc03d/download)

**Comment by rinkeshbhutwala** [comment]
As discussed with @vinod-kadam on stand-up first try to fix the other bugs of v2 which are blocking for LFX and high priority so will work on this ticket later on because this is a big task for migrating all v1 endpoint to v3 go-lang endpoints.
