### ISSUE TITLE
Migrate EasyCLA from lfcla.com to easycla.org

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#805]
## Summary

Migrate EasyCLA from lfcla.com to easycla.org

## Background

The product teams would like to transition the domain for EasyCLA from lfcla.com to easycla.org.  In order to support this, we will need to prepare the software and infrastructure configuration.

## Tasks

- [ ] UI - Review and update legacy UI CORS configuration (PMC, Corp Console, Contrib Console)
- [ ] UI/API - Develop a migration plan for affected SSM parameter values in each environment
- [ ] Infra - Review and update serverless configuration for Certificates
- [ ] Infra - Review and update serverless configuration for legacy API GW
- [ ] Infra - Review and update serverless configuration for Route53
- [ ] Infra - Review and update GitHub App settings for DEV, STAGING, and PROD
- [ ] Infra - Review and update DocuSign links/URLs/Callbacks

Questions remain:

- [ ] will this only impact PROD or will it impact DEV and STAGING as well?
- [ ] what is the timeline schedule?

## User Story

As a product owner, I want to switch the EasyCLA product to a different domain.

## Acceptance Criteria

EasyCLA running on easycla.org

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Will not be migrating to easycla.org.
