### ISSUE TITLE
API - Add Signature Queries to V2

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#817]
## Summary

Add the Golang V3 Signature Queries to V2.

## Background

Add the Golang V3 signatures to the V2 swagger specification and ACS CLI configuration.

## Tasks

- [x] Review the v1 Swagger specification related to Signatures (see references below)
- [x] Add V2 Swagger Specifications - reuse data models
- [x] Add ACS CLI definitions for endpoints

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [Signature API by ID](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L390)
- [Signature API by ID again](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L421)
- [Signature API by Project ID](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L454)
- [Siganture API by Project and Company](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L491)
- [Signature API by Company](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L528)
- [Signature API by User](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L561)
- [Signature API by Employee](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L594)
- [Signature GH Org WL](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L632)

**Comment by prasannamahajan** [comment]
Pull Request: https://github.com/communitybridge/easycla/pull/831

**Comment by nirupamav** [comment]
**_Testing In Progress_**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/CLA+Singatures+V2

**Comment by dealako** [comment]
Queries are completed for v2. Closing ticket.
