### ISSUE TITLE
Migrate DB Project Table - Added Project Lower Case Column Value

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#925]
## Summary

Migrate DB Project Table - Added Project Lower Case Column Value

## Background

Write a database script to migrate/update the existing databases to properly set the project_name_lower db column.

## Task

- [x] Write DB migration script
- [x] Perform migration on DEV
- [x] Validate/Verify
- [x] Create PR
- [x] Notify @dealako when complete

## User Story

As a EasyCLA user, I need to be able to query the database for case incentive records for CLA Groups.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by vinod-kadam** [comment]
David to review it.

**Comment by dealako** [comment]
Resolved - project_name_lower has been addd to DEV, STAGING, and PROD.

![Screen Shot 2020-11-30 at 4.01.17 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/aa31a5f7-5820-4f23-a6c7-18f30c18bb3f)

Closing this ticket out.
