### ISSUE TITLE
Update Project Management Console SFDC Python Logic

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#947]
## Summary

Update Project Management Console SFDC Python Logic - Replace with API calls to the Platform Project Service.

## Background

The current implementation utilizes a direct API call to SalesForce. As a platform, we are migrating these direct API calls to now leverage the Platform Project Service.  The reasons are:

- Avoid hitting the SFDC API Limit
- Leverage existing Project Service integrations
- Support common API and permissions model
- Control machine and scaling

## User Story

As a systems integrator, I want to migrate the direct SFDC API calls to leverage the Platform Project SErvice

## Tasks

- [x] Review easycla-tools - [get projects by ID](https://github.com/LF-Engineering/easycla-tools/blob/master/dynamodb/get-ps-projects.py) logic that fetches an access token and makes Project Service API calls
- [x] Review the [existing EasyCLA APIs that need migration](https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/salesforce.py#L193-L195)
- [x] Replace the existing EasyCLA SFDC API logic with calls to the Platform Project Service
- [ ] Write a set of functional test
- [ ] Test and Validate

## Assumptions

- [x] relevant configuration parameters are available in SSM

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
**_Verified below scenarios. There are few issues which were there even before this ticket was fixed and few new tickets are logged which are listed below against the test sceanrio_**
| Scenario  | Status | Bug | Comments |
| ------------- | ------------- | ------------- | ------------- |
| Foundation name, logo and description in All Projects page| Passed  |#1049 | |
| LFX logo and link in menu options in All Projects page| Passed  | | |
| All Projects link in menu options in All Projects page| Passed  | | |
| Sign Out link in menu options in All Projects page| Passed  | | |
| Add invalid github organization | Passed  | | |
| Add duplicate github organization | Passed  | | |
| Configure and install valid github organization | Passed  | | |
| Delete the configured github organization | Passed  | | |
| Add CLA Group | Passed  | | |
| Update CLA Group | Passed  | | |
| Delete CLA Group | Passed  | | |
| Duplicate CLA Group | Passed  | | |
| Generate templates for CLA Group | Passed  | | |
| Back to Project from All pages of SELECT TEMPLATE | Passed  | | |
| View templates for CLA Group while generating templates | Passed  | | |
| View templates for CCLA and ICLA from View PDF History| Passed  | | |
| ICLA contribution end to end flow| Passed  | | |
| Company signature flow| Passed  | | |
| Employee contribution end to end flow when employee is whitelisted| Passed  | | |
| Signatures and Pagination in View Signatures| Passed  | | |
| Companies and Pagination in View Companies (From both View Companies button)| Passed  | | |
| Add Github repositories to CLA Group by clicking ADD on particular repositories| Passed  | | |
| Add Github repositories to CLA Group by clicking ADD ALL REPOS| Passed  | | |
| Remove Github repositories to CLA Group by clicking REMOVE on particular repositories| Passed  | | |
| Add Github repositories to CLA Group by clicking REMOVE ALL REPOS| Passed  | | |
| Foundation name, logo and description in Project Details page| Passed  | | |
| Back to All Projects from Project Details page| Passed  | | |
| Header and Footer in all pages of Project Console| Passed  | | |
|EasyCLA Documentation link in all pages of Project Console| Passed  | | |
|Help link in footer in all pages of Project Console| Passed  | | |
|EascyCLA logo in all pages of Project Console| Passed  | | |
